### ISSUE TITLE
Fel Rock/Ben'ethil Barrow - Aggro Issues

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#102]
Map & Area: Teldrassil - Fel Rock
How to replicate the bug: Just enter Fel Rock

The first sprite reacts normally however on entering the cave the first time, as you move into the cave you then get several sprite aggro at once thus making it impossible to enter the cave.  I tried this a second time, it appeared to react normally then all of a sudden I had several sprites respawn behind me.  However, some of these are ones you encounter further in the cave so shouldn't have been there.

What should happen: The sprites should be spread normally and singularly, respawn timer should be greatly increased.

Also found a similar problem in Ben'ethil Barrow: Shaman charged (they shouldnt do that) also kept trying to go behind me when I was not in aggro range, respawn very quick on some mobs to the point you get overwhelmed.

**Comment by cala** [comment]
I agree. There is a lot of place, especially caves/mines where the mob density is too heavy and/or respawn timer to short: Fel Rock, Jasperlode Mine, Ben'ethil Barrow, Dor'lamin Barrow...
Prior to doing anything, it would be best to check how it is on TBC and WotLK. But this needs to be fix because these places are nightmare when soloing and they should not.

**Comment by Schmoozerd** [comment]
maybe use some pooling system for these "mines" - to limit the amount of mobs spawned in the same moment (max_limit = 10 or such for whole mine)

**Comment by cala** [comment]
I did some tests yesterday and the day before and I think several things are involved here.
- 1. spawns are mostly the same between UDB and Classic DB, with perhaps a few more for Classic DB but nothing that would matter. This is good news as we won't have to add/remove spawns or create pools for them (thank you @Schmoozerd for this suggestion)
- 2. respawn time seems to be too quick making mobs respawn right on top of low DPS character (healers, tanks) before they finish killing the next mob
- 3. it is very common when pulling a mob to have at least one more coming too, even when range pulling, making these places tough for casters. This means assistance radius might be slightly too big
- 4. aggro range seems also slightly too big
- 5. I discussed with @Cyberium about half a dozen of creatures in Fel Rock (and maybe somewhere else) that might have a random movement generation issue making them want to climb on the top of the moutain Fel Rock is in. As such, they all move out of the cave in a queue. This is probably when @scotty0100 aggroed a lot of them.

Bullets 3 and 4 are probably also relevant for whole world and not only caves/mines. However, because players are trapped in a gauntlet down there, these issues are probably more visible. These can be fixed by tuning down the values of `Rate.Creature.Aggro`, `CreatureFamilyFleeAssistanceRadius` and `CreatureFamilyAssistanceRadius` in `mangosd.conf` core configuration file.

Regarding bullet 1, I think spawns are ok.

Regarding bullet 2, I'm not sure if respawn time is really an issue or if players spend too much time killing mobs due to assistance/aggro radius being too big and thus get caught by respawn when they should'nt

Regarding bullet 5, I'll fix Lord Melenas within the day as it has the same strange behavior but is a quest objective. For the half dozen of imps having also this issue, I suggest you wait a few minutes before entering Fel Rock, giving them time to leave it. I'll fix them later one by one.

**Comment by cala** [comment]
The true issue here is bullet 5 and random point generation. This is a core issue that was fixed on master in https://github.com/cmangos/mangos-wotlk/commit/1b07104557529b2a56ed5cbe757f22c285237514 by @cyberium and will be port later to Classic. So, I'm closing the issue here as nothing is to be done DB-side.
