### ISSUE TITLE
Quest: Deep Run Roundup (6661)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#105]
Might need SD2, but I think DB scripting should be OK.

.go creature Monty

Objective: Use the flute to enthrall 5 rats and take them back to Monty

5 rats are enthralled but when you take them back to Monty the quest does not complete.

What should happen: Once you get all 5 rats to Monty, quest should complete.

Correct behavior:
A youtube video of how the quest should work: www.youtube.com/watch?v=U11BArF432g

Links:

Deeprun Rat: http://www.wowhead.com/npc=13016/deeprun-rat
Enthralled Deeprun Rat: http://www.wowhead.com/npc=13017/enthralled-deeprun-rat
Deeprun Rat Roundup quest: http://www.wowhead.com/quest=6661/deeprun-rat-roundup
Monty(quest NPC): http://www.wowhead.com/npc=12997
Melodious Rapture(possible animation spell): http://www.wowhead.com/spell=21050

A youtube video of how the quest should work: www.youtube.com/watch?v=U11BArF432g

**Comment by cala** [comment]
Thanks for the report. This quest was recently added via SD2 and I would expect it to work. Maybe I forgot something when porting the related database update to Classic DB. I'll have a look at it.

**Comment by Tobschinski** [comment]
The script on quest_end is missing. The rats should run to Monty, he will say some related text, use an emote and the rats should despawn.

This is needed because otherwise the Enthralled Rats will never despawn and blocking the respawn of the Deeprun Rats for other players.

With 14 Rats alive, the quest will be broken after 2 players have completed it.
