### ISSUE TITLE
Grime-Encrusted Ring never drops from Dark Iron Agents (Gnomeregan)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#131]
Grime-Encrusted Ring has negative drop chance in ClassicDB, so it never drops because it is not quest collection item (it begins quest itself).

UPDATE `creature_loot_template` SET `ChanceOrQuestChance`=6.9582 WHERE  `entry`=6212 AND `item`=9326 AND ChanceOrQuestChance=-100;

Drop chance: YTDB = 6.9582%, Trinity Core DB = 8%

**Comment by Schmoozerd** [comment]
probably reasonable is 10%

But i think you should put a condition: "CouldStartQuest" or something related - and clearly not drop it if the quest is already done/active or the item in the inventory?

**Comment by cala** [comment]
I agree 10% is probably the most reasonable value. However, UDB has 8% and I will probably stick to this in order to avoid introducing more unneeded gap between UDB and Classic DB.

Regarding the condition, I would say "yes we should put a condition" if we were dealing with TBC-DB or UDB. But I clearly remember looting a quest _starting_ item in back in Vanilla days even with the quest complete. The item was however unusable ("You already completed that quest" or some similar error message).
It was changed later, but I can't say if it was during Vanilla days or later in TBC.

If we add such a condition (and we can chose to do it), then every quest starting item looted from creature/GO should have similar condition.

**Comment by Schmoozerd** [comment]
it might be reasonable to consider the negative dropchance of items that start a quest as condition (on >= tbc) for quest possibility; but this would be a not entirely simple core change likely, as the loot system is not too easy to understand..

**Comment by cala** [comment]
On a side note, I will have to discuss with a core dev about the loot system later as I'm pretty sure there is a small issue with items dropping with conditions (at least when they drop in not Free For All).

**Comment by hribsatan** [comment]
Grime-Encrusted Ring quest cannot be obtained because this item http://database.wow-one.com/?item=9326  dont drop from dark iron agents, checked this 2 days ago kill almost 20-30 dwarfes and no drop.

**Comment by cala** [comment]
@hribsatan Thank you for taking the time to check if something related to your issue already exists. I appreciate it. :+1: 

I just checked the database and the item has a low drop chance but it does drop. With about 30 Iron Dwarves killed without a drop, I may say that you are just unlucky. Yes, the link you posted say that it has a 100% drop chance, but private servers like this one have often wrong data (let it be intended or just a mistake). In this case, wowhead has a far more realistic drop chance.
