### ISSUE TITLE
Frostmane Headhunter - Throw - Bad Visual

### ISSUE THREAD

**Issue by PatSmuk** [classicdb/database#136]
When Frostmane Headhunters use their scripted Throw ability the projectile is a small checkered cube.

**Comment by cala** [comment]
Thanks for the report. I think this is the same thing as #103 
It seems that every NPC with a throwable weapon will throw small cubes instead of the weapon model. I did not see in the DB something that explains this (but equipment table is different of what it is in TBC/WotLK). Thus I assume it is somehow related to core.

**Comment by cala** [comment]
I'm doing a bit of clean up in the issues. This one is already open in #103 though no progress so far.
