### ISSUE TITLE
Tauren quest "taming the beast"

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#153]
Using 27/10/2013 DB.
- Swoop, stalker and plainstrider are instant cast spells, instead of 10 seconds.
- When you get the last skill "beast tame" at thunderbluff and wanna go tame some pets. Skill is instant as previous 3 and no pet can be tamed.

**Comment by cala** [comment]
Thank you for this report. When you have an issue with a quest, can you also give the quest number to help fixing it. Select your character and type `.lookup quest name the quest with the issue` . You should get a list of all the matching quests with a [active] or [complete] along the one you are currently having an issue.
I ask this because there are about twenty quests named "Taming the beast", so testing every single one is a bit tedious.

**Comment by Metalica** [comment]
Sry about that. Will go and and check it out.

 Tauren: Taming the best

 Part 1 ID: 6061
 Part 2 ID: 6087
 Part 3 ID: 6088

 Tauren: Training the beast

 Part 4 and last part: 6089

**Comment by Metalica** [comment]
Also Tested the whole quest line for ORC hunter and it works.

**Comment by Metalica** [comment]
Tested, all working. This ticket can be closed.
