### ISSUE TITLE
[BlackRock Depths] Arena functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#177]
- The spectators are to become neutral once you beat the arena.

**Comment by Schmoozerd** [comment]
this is an sd2 issue
poke @xfurry for this.

Should be a simple enough change however: store spectators in a GuidList, iterate it on finish and change faction
maybe somebody else is also interested in it.

**Comment by xfurry** [comment]
Well the question is: are the spectators changing faction, or do the players get a forced faction aura?

Probably it's the first option, but in this case we also need to know the faction id.

**Comment by PatSmuk** [comment]
Most likely the spectators change faction since there's no force reaction spell like this. Their faction is 54 and since most of the enemies in the dungeon are this faction (and don't change reaction) then its the spectators that change.

**Comment by cala** [comment]
@Schmoozerd 

> Should be a simple enough change however: store spectators in a GuidList, iterate it on finish and change faction
> maybe somebody else is also interested in it.

I'm interested and gave some thoughts into it. However, the spectators are not just several spawns of one NPC entry (like [Arena Spectator](http://www.wowhead.com/npc=8916/arena-spectator)), but there are several entries: [Arena Spectator](http://www.wowhead.com/npc=8916/arena-spectator), who are found only there but also : [Shadowforge Citizen](http://www.wowhead.com/npc=8902/shadowforge-citizen) or [Anvilrage Medic](http://www.wowhead.com/npc=8894/anvilrage-medic) who are found elsewhere in the dungeon as hostile NPCs.

So if we want to store the ones in the arena in a GuidList, we need to know their GUID first hand since we can't store all NPCs of those entries.
Another approach would be to target all NPCs in a defined radius around the arena center and change their faction. Which one do you think is better?

**Comment by evil-at-wow** [comment]
I would suggest a combination of both. The GUIDs no doubt vary between databases, so that's annoying. And I'm not just speaking about the difference between WoTLK/TBC/Classic. Some cores have different databases to choose from, like UDB/YTDB/PSMDB for WoTLK. With that in mind, hard coding GUIDs in the SD2 script is not a good idea. Your sectond option, searching in the arena, seems to be the better option, but the tricky part with a search is to get it right in this case. You would have to do the search right after the instance is spawned, and I'm not sure that's possible. If you don't, and for example do the search the moment the arena event is completed, you risk finding creatures in the arena that you didn't want to target. The most obvious is Dark Keeper Zimrel and his guards; they can be summoned before you start the arena event but they should stay hostile all the time. And at least theoretically speaking, there are other possibilities to exploit. For example, some players could be doing the arena event, while other players in the group are not; these could then pull and kite other mobs to the arena steps that might end up in your search and turn neutral, while they shouldn't. I agree it's far-fetched, but it's possible.

So, let's not make this too complex and just combine both strategies:
- Define a fixed volume that describes "on the arena steps". For example, a small cylinder around the arena spectator's center (to account for z-coordinates too). That gives an easy check to do (with R the constant radius of the cylinder): `z_lower <= z_creature <= z_higher && (x_creature - x_center)^2 + (y_creature - y_center)^2 <= R^2`.
- Use the InstanceData's OnCreatureCreate call to fill a GUID list, and implement it as a simple switch of creature entries you expect to be arena spectator's. For those, run the check and add them to the GUID list if they pass it.

Advantages:
- Called whenever a creature is spawned, so you'll be using the spawn position when running the check, which means you'll only include creatures that actually spawn on the arena steps.
- Easy to ignore creatures like Dark Keeper Zimrel and his guards.

Disadvantages:
- None, except that it's slightly more complex that a hard coded list, or simple search.

**Comment by cala** [comment]
Thanks @evil-at-wow that indeed sounds like the best way to do it. The hardcoded GUID list would indeed be easier but would be a poor way to do it for the reasons you've listed and that was implicit in my previous post.

So, I'll prefer what looks like the proper way over the easy one. I'll propose a patch for this in SD2 soon.

**Comment by cala** [comment]
Fixed in SD2 https://github.com/scriptdev2/scriptdev2/commit/7624584660798961de5eb726f9e18495f5e75a08 and pending backport to Classic branch that will happen in due time. Thanks everyone! :+1:
