### ISSUE TITLE
Some outdoor models cause dismount

### ISSUE THREAD

**Issue by cala** [classicdb/database#19]
Certain outdoor models cause players to dismount, such as the bridges in STV or the entrance to Everlook.

_original report by [The-Great-Sephiroth](https://github.com/The-Great-Sephiroth)_

I'm not sure this is indeed an issue as I remember such behavior from classic, though it was changed later.
It would probably be better to open an issue per place.

**Comment by cala** [comment]
Close issue as players no longer dismount in the place listed above. Was obviously not DB related.

**Comment by DomGries** [comment]
Really? Did you test it at the specified locations?

Would be pretty neat if it was a false report because 1. this is a core issue and 2. I would not know any better values than we currently use to determine if a model is indoor/outdoor... see https://github.com/cmangos/mangos-classic/commit/b389053cfb728cf46497bf7cf8342c758b2e6eb4

**Comment by cala** [comment]
I did test at the specified locations, several time and I took care of typing `.gm off` before to be sure.

Note that this issue was imported from mangoszero database repository and as such could be relevant only for their core.
