### ISSUE TITLE
[Stratholme]  Stratholme Dead Mechanics

### ISSUE THREAD

**Issue by ghost** [classicdb/database#191]
- Three or four Shades patrol around invisible. When they aggro they break invisibility and after a duration of time spawn   adds before disappearing. They do not spawn more if they are killed first. {I encountered none citation needed}

**Comment by cala** [comment]
The spawns are fixed by https://github.com/classicdb/database/commit/4338bcf93042448518e847c742136b22a65fe83f but I'll let this issue open until the AI is also improved.

EDIT: the EventAI script already exists. Needs to look what is wrong (creature does not seem to aggro, needs to remove aura first?).

**Comment by Tobschinski** [comment]
Invisible units can only see other invisible units, or units, that can detect invisible units (due to a spell). Therefore, most players are ignored.

The target for the spellcast needs to be scripted, since the Eye will never target anyone.
Targets (46, 0) (TARGET_SCRIPT_COORDINATES, NO_TARGET)
