### ISSUE TITLE
[Dire Maul North] Tribute chest mechanics and functionality.

### ISSUE THREAD

**Issue by ghost** [classicdb/database#203]
- Tribute chest should not be spawned till after the king dies.
- Mizzle the Crafy is meant to be spawned after you kill King Gordok with Cho'rush alive. Mizzle comes to confirm it and     gives the party King of the Gordok. Further dialogue spawns the Tribute chest with an extra piece of loot for each      overseer left alive.

**Comment by scotty0100** [comment]
Had a go at fixing this via the DB, but there's a lot of conditions to be met which I'm not sure is fully achievable through the DB?

We need to check outstanding mobs that are up and place loot in the Tribute Chest based on how many Overseers are alive etc.

Was experimenting with 36   CONDITION_DEAD_OR_AWAY for at least the gossip menus; but didn't have much luck there either.

This is quite a big bug because it enables players to get unlimited amount of green/blues for disenchanting =x

**Comment by Schmoozerd** [comment]
DireMaul loot is supported via SD2.
https://github.com/scriptdev2/scriptdev2/commit/d3d57a333f6ada53177ef463468b0c0a97785b73

It is likely you can find the related loot-tables in udb or cmangos forums or some other commit-comments.

**Comment by evil-at-wow** [comment]
I don't remember seeing the Dire Maul Tribute chest loot in some database, but I'm sure it's possible to do because master @Schmoozerd has taught us how to do it by providing hard mode loot for [Sartharion](https://github.com/scriptdev2/scriptdev2/commit/a55180dde0409e200f72784c1735c6d2eb35f045) and [Zul'Aman](https://github.com/scriptdev2/scriptdev2/commit/7d5cff4bee9208afbe6aa1e23896ca8bce11b675) (see the first comment for reference SQL).

**Comment by cala** [comment]
Fixed by https://github.com/classicdb/database/commit/94a05ca598dc32a62d531aa43f4ae831511afda4
