### ISSUE TITLE
[Upper Blackrock Spire] Doodad functionality

### ISSUE THREAD

**Issue by ghost** [classicdb/database#207]
- Braziers leading to the door to UBRS are targetable and usable. They are meant to light up 2 at a time then the door opens when you are attuned and go to open the door.

**Comment by cala** [comment]
This one will probably be fixed by a mix of database and scripts. If we want to be 100% blizzlike, the doors should have a script linked to them that perform a range check on nearby players. If on of them have the seal of ascension (in his inventory or equipped), the doors should automatically open and the braziers light up. This requires SD2.
Another approach 100% database would be to add a script on GO use to light up the braziers when a player opens the doors. This one is not 100% blizzlike but is easier to do.

**Comment by ghost** [comment]
I should change this to quality of life, it isn't really a necessary change.

**Comment by Schmoozerd** [comment]
There is a areatrigger just in front of the door - so i think this one should be used for check and dependendly opening the door.

**Comment by cala** [comment]
Thank you for the input. Though I know what is the purpose of areatriggers, I don't know how to access them. I guess the best (and maybe only) way is to use SD2, like in the Murkdeep murloc quest in Darkshore? This would lead to some script like:
- when area is triggered : check if player has item in its inventory
- if so, activate the GOs (braziers and doors)
- assign a boolean value to prevent the script to run twice

**Comment by Schmoozerd** [comment]
exactly:
https://github.com/scriptdev2/scriptdev2/blob/master/scripts/eastern_kingdoms/blackrock_spire/instance_blackrock_spire.cpp#L647

Add

```
DoOpenUpperdoorIfCan(pPlayer);

and a new method:
void DoOpenUppderdoorIfCan(Player* pPlayer)
{
  if (m_bAlreadyOpened)
    return;

  if (pPlayer->HasItem(THE_KEY))
  {
    DoUseDoorOrButton(UPPER_DOOR);
    // Activate the other GOs
    m_bAlreadyOpened = true;
  }
}
```

possible you should infact check all players within the map, this depends on the logic

**Comment by cala** [comment]
Thanks again!
I'll write and push a script when I can spare some time on this one. Regarding the logic, the door only opened when a player "attuned" (having the item and even wearing it in the early versions) came near the door. So I guess performing a check for all players in the map is not necessary, only those entering the areatrigger.

**Comment by cala** [comment]
In scriptdev2-tbc, pending backport to Classic.
