### ISSUE TITLE
No Loot from NPC "Singer" (rare Female Human, Arathi Highlands)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#217]
INSERT IGNORE creature_loot_template SET entry=2600, item=5180, ChanceOrQuestChance=30, groupid=2; -- uncommon Necklace of Harmony
INSERT IGNORE creature_loot_template SET entry=2600, item=5181, ChanceOrQuestChance=67, groupid=2; -- uncommon Vibrant Silk Cape
DELETE FROM reference_loot_template WHERE item IN (5180,5181);

PSDB contains most balanced chance values for this case.

**Comment by cala** [comment]
Thank you for this report. I will push a fix later but with changing the drop rate of item 5181 to 70 (or 0) instead of 67.
As this is a group, the loot system will always want to pick at least one item in the group. But currently the sum of the `ChanceOrQuestChance` is 30 + 67 = 97 < 100 and this could lead to unexpected behaviours, the least one being 3% chance of no drop.

**Comment by Neotmiren** [comment]
It appears to me that sum of chances < 100% also works (strict 100% is required in some other situations). It worked for me in practice and also there is commentary in LootMgr.cpp

// Rolls an item from the group, returns NULL if all miss their chances

which presumes that it is possible to roll nothing from certain groupid.
