### ISSUE TITLE
[Onyxia's Layer] Fight mechanics

### ISSUE THREAD

**Issue by ghost** [classicdb/database#227]
- takes damage from fire {originally immune}
- Nearing the whelp caverns does not spawn whelps at all, nor does entering them.
- She does not let off an emote when using deep breath.
- After the fear is over {bellowing roar}, the lava cracks spew forth lava for a few seconds. Characters hit with the lava take about 1,500          points of fire damage (unresisted). {Currently does 0 damage}
- Whelp spawning doesn't persist in to phase 3.
- Always drops 2 t-2 helms. {Sometimes only drops one currently}

She seemed to use walking animation while flying.

Citation
http://www.wowwiki.com/Onyxia_(original)

**Comment by cala** [comment]
Thank you for this report. There are many things involved here, I think.
- Some immunities and gameobjects are clearly missing (can be fixed in DB)
- The missing emote is probably a core issue as currently NPCs are unable to use text emote in Classic (like "Onyxia is taking a deep breath" written in orange). This is in the way of being fixed
- The T2  helms is also a core issue. I made a few months ago an update in Classic DB preventing shaman T1/T2 items to drop for Alliance (and vice versa for Paladin items / Horde) like it was in Classic. For this, I added a condition in the `creature_loot_template` table. However, the issue you're mentionning appeared. After looking into the loot code in core, it seems that items are rolled _before_ the condition is applied. This means that Onyxia (and every mobs that can drop T1/T2 items) does drop 2 items, but when one of them is of the opposite faction, players can not see it. I think core should apply conditions before rolling for items, not only regarding this issue, but also to prevent items that won't be seen by players to take a spot in the loot table (when group are involved). Unfortunately, I don't understand the code well enough to fix that easily. I'm not even sure that it can be fixed easily as loot code is pretty complex.
- The whelp issue and players not taking damage from the lava cracks: no idea yet without first looking at SD2 code to see what gameobjects/creatures are involved

**Comment by ghost** [comment]
The whelps are two things, area trigger for when getting close, then at the transition in to phase 2 where they spawned continuously periodicity till the fight ends. As well as the area trigger spawning whelps too.
Is there maybe a way to create two loot tables for each boss? one with alliance loot and one with horde? Then it pulls  one base based on faction?

**Comment by Schmoozerd** [comment]
@cala - it was fixable by creating conditions that are evaluated before the player is processed.
ie loot-condition applied to a reference.
However for this case one would require the raid to be "marked" as alliance (or horde), which also would require some extra work.

Atm such behaviour can be modelled with SD2 easily (we defined the side of the raid currently as the side of the first player entering).
However maybe it might be a good idea to create a core side check and condition for this.

But also keep in mind that this ONLY an issue because we have possibility of mixed groups as custom feature.

**Comment by cala** [comment]
If I understand this correctly:
- all the T1/T2 items should be moved to `reference_loot_template` along  those with the alliance/horde conditions (in order to keep the drop chances equal)
- in order to let the core evaluate the condition, a SD2 script should be written for the related instances (MC, BWL and Onyxia Lair) assigning the group's team

Hem... I'm pretty sure I missed or misunderstood something there... :/

**Comment by Schmoozerd** [comment]
Nope, this would be a possibility how to deal with it.
However I really DO think defining ally/horde should not be done by sd2 but by core.

But infact i see absolutely no reason to change the current behaviour.
It only affects the CUSTOM case of mixed groups - and a server allowing this should also has no problem with a few T items having slightly increased loot-chances.

**Comment by PatSmuk** [comment]
@Nekoi Unfortunately there are no areatriggers for the whelps right now so it's a bit trickier. There's a creature called "Onyxia Trigger" which presumably is used to do that.

@Schmoozerd Do you mean that the item drops work currently, or it still needs a patch for SD2?

**Comment by Schmoozerd** [comment]
the drops work correctly (should be doable correctly) for the case of non-mixed raid groups.

**Comment by cala** [comment]
Except for the animation while hovering that probably requires specific code in core, everything here is now fixed.
