### ISSUE TITLE
[Quest] CLUCK! (3861)

### ISSUE THREAD

**Issue by ghost** [classicdb/database#228]
- This is the quest where you are to do the /chicken macro 100 times to make the chicken friendly. Then you give him the special chicken feed to get the non-combat pet
- Only takes a few /chicken to activate friendly status
- Does not register if you have the feed in order to turn the quest.

Citation
- quest http://db.valkyrie-wow.com/?quest=3861
- item for turn in http://db.valkyrie-wow.com/?item=11109

**Comment by cala** [comment]
Thank you for this report. This issue is already open: https://github.com/classicdb/database/issues/16

> In Westfall, the quest Cluck! (3861) requires Special Chicken Feed (11109) but the quest is not completable. The chicken becomes friendly after you emote /chicken 50 times, but even if you buy chicken feed or use ".additem 11109" it still does not meet the requirement.

I'll close the first one as yours is a bit more detailled.
- Regarding the 100 x /chicken : there is no proof that 100 is the correct value, some say it's 50, some other that this is less. It very much looks like the value is random and this is the approach used by the SD2 script handling this quest (https://github.com/scriptdev2/scriptdev2-classic/blob/master/scripts/world/npcs_special.cpp#L41)
- I checked this quest several times and I think this issue cannot be solved by DB as the `creature_questrelation`, `creature_involvedrelation` and `quest_template` tables are the same between Classic DB and UDB, yet the quest is working in WotLK and not in Classic (did not test TBC). The script also look the same between the two versions, so I have to ask core or script devs their opinion on the matter because I suspect the quest completion mechanics to be different between the two versions.

**Comment by Tobschinski** [comment]
The combination of `method`='2' and `special_flag` | 'repeatable' does not work if the NPC has only one quest available (-> no opened gossipmenu to choose quests from) . 
Toggle any of the mentioned conditions and you can properly choose, accept  and complete the quest.

That's for sure something in the core.

**Comment by cala** [comment]
Yes, that's what I was speaking about. I did not took the time to speak of this to cyberium, schmoozerd or xfurry though.

**Comment by cala** [comment]
Closed by 
https://github.com/cmangos/mangos-classic/commit/185e72c04cc518064665fd66c7730aae69d6c468
