### ISSUE TITLE
[Gossip] Class Trainers Display Wrong Gossip For Right Class

### ISSUE THREAD

**Issue by PatSmuk** [classicdb/database#230]
Gossip trainers give you a rejection message even if they are the proper class, i.e. the warrior trainer will tell you that you aren't a warrior even if you are. They still have the right options available though.

**Comment by cala** [comment]
Thanks Patman.
A lot of gossips, especially trainers were fixed in https://github.com/classicdb/database/commit/02840271ed1d11101d495dbcf2ff6adb57e66a03 .
I tested some of them, mostly rogue trainers and they seemed to work as intented.
Thus, your report means that some trainers have either:
- the wrong condition to switch from a gossip to another
- only one text available and as such, only display this one

Could you please provide me we a few trainers names or entries with the wrong gossip? I'll have a look at them. Thanks again.

**Comment by PatSmuk** [comment]
I was looking at Arias'ta Bladesinger (ID 4087) in Darnassus.

**Comment by cala** [comment]
After checking this NPC, it appears she does not have conditions attached to her gossip menus. I'll fix this soon.
More trainers or vendors with gossip changing with player faction/reputation may have similar issue. Please, feel free report them as you find them.
