### ISSUE TITLE
[PVP] [PVE] Parry attacks from behind

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#236]
Right now, mobs can http://www.wowwiki.com/Parry attacks from behind.
The shown mob parried twice in a row while running away in fear. 

![parryfrombehind](https://f.cloud.github.com/assets/4753528/2062054/11770906-8c79-11e3-99fa-ee409a8878ae.png)

It should be like

![parrynotes](https://f.cloud.github.com/assets/4753528/2062055/15afb360-8c79-11e3-9696-f820e6be53c7.png)

**Comment by cala** [comment]
Thank you for this report. Like some of the previous, I think this issue can only be handled by core. Thus, I suggest you to re-open this issue here: https://github.com/cmangos/issues/ instead. Like other issues opened here, you can add a link pointing to here to help keep track of the whole discussion.
I'll probably close this one in a week or two.
