### ISSUE TITLE
[NPC] AI with ranged/spellcasters

### ISSUE THREAD

**Issue by ghost** [classicdb/database#244]
- Most if not all spell casters do not try and create Line of sight if it is lost, they generally just stand there and stare.

![capture](https://f.cloud.github.com/assets/6431336/2089017/ec8602fe-8e81-11e3-8c73-3e7b0bce0560.PNG)

**Comment by cala** [comment]
Thank you for this report. Like the other one, I'm afraid we can not do very much from the DB side and this can only be fixed by core. Two issues involving this are already opened there:
https://github.com/cmangos/issues/issues/180 (dedicated to this)
https://github.com/cmangos/issues/issues/308 (more generic about mobs AI)
