### ISSUE TITLE
Hunter Taming Attack Speed.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#246]
[This may be a code issue rather than DB.]

Just got around to taming some pets which should have different attack speeds, Broken Tooth most famously which is supposed to have a 1 second, caster-killer attack speed.

However, all the pets I tamed so far, including Broken Tooth have the default 2 second attack speed. In reality, a lot of pets should have unique attack speeds. For example, Rak'shiri (rare aqua-coloured saber in Winterspring) should have a 1.5 second attack speed but he/she also has 2.0 instead.

Here's proof for Broken Tooth:

http://www.wowhead.com/npc=2850#comments:id=3315

Further proof with a comprehensive list of pets/beasts and what attack speeds they should have:

http://web.archive.org/web/20061112230516/http://tkasomething.com/attackspeeds.php

**Comment by cala** [comment]
Thank you for this report and this is both a core and database issue.
- Database because the pet creatures all have a 2000 ms attack speed while they should have something more variable (and the link you posted is very usefull in this matter to fix those values)
- Core because the core currently does not use the attack speed value from database but uses instead a flat value (which is correct for TBC and beyond, but not for Classic). I'm not sure an issue regarding this is opened core side. If not, one should be opened.

**Comment by scotty0100** [comment]
Raised a core issue.
