### ISSUE TITLE
[Molten Core] Shazzrah

### ISSUE THREAD

**Issue by ghost** [classicdb/database#254]
- Arcane Explosion does double it's intended damage.
- Does not blink every 45 sec to a random target causing threat wipe.

Citation
http://www.wowwiki.com/Shazzrah

**Comment by Tobschinski** [comment]
does not patrol around the rune.

~~missing his weapon~~

**Comment by cala** [comment]
Tested right now:
- Blink is working. The spells is not 100% perfect due to missing dummy effect in core, but it works
- Arcane explosion does its expected damage. The values are only double when Shazzrah Curse is active (double arcane damage taken)

So, only the patrol path needs to be looked at now (weapon was fixed in [0646]).

**Comment by Tobschinski** [comment]
He uses his teleport twice, due to the used hack. 
And the forced Arcane Explosion Cast is probably wrong, as I have seen him doing other casts first.
(Since he is teleporting twice, he will cast two of them which will do ~4000 AOE damage instantly)

I think all that is necessary is to set the timer to 0. But thats SD2 stuff ...

**Comment by cala** [comment]
I did not see him teleport twice, but having done my tests with only two players, it is very possible that I missed this. I don't see in SD2 why he should teleport twice... unless the spell in core was fixed (to be checked).

I agree the forced cast of arcane explosion is probably wrong.

**Comment by Tobschinski** [comment]
Yes, the spell works perfectly. Although it could be helpful to know what was considered bugged. :)

Anyway, as I am currently trying to improve the scripts in MC, I have to add one thing, since we are already talking about SD2 bugs.

Magic Grounding should be a buff, not a debuff. (and therefore dispelable)
This happens at multiple occasions in MC. (Majordomo shields etc.)

**Comment by cala** [comment]
To be honest, I'm not sure where spells are flagged as buff/debuff. I suspect this is their attributes in DBCs, which means that if DBCs are wrong, we need to add an exception to them in core.

**Comment by cala** [comment]
Waypoints added in https://github.com/classicdb/database/commit/cd239358fba6608be44e4228ec3949a9b88edba7

**Comment by cala** [comment]
Are there still DB related issues regarding Shazzrah? Or can we close this and let SD2 deal with the script improvements?

**Comment by Tobschinski** [comment]
Nope.
