### ISSUE TITLE
[Molten Core] Ragnaros

### ISSUE THREAD

**Issue by ghost** [classicdb/database#258]
- Majordomo's body stays to long
- becomes unengagable after 1 wipe.
- Melt weapon does not seem to be functioning
- Magma blast is meant to do 4k-6k always does 6k
- submerging animation bugs out and he is shown standing there.
- Son of flame do physical instead of fire.{unsure if aoe mana drain functions}
- Unsure of banished sons count as dead ones to cause rag to emerge premature.{They are suppose to.}

Citation
http://www.wowwiki.com/Ragnaros_(tactics)

**Comment by cala** [comment]
Summoning @Tobschinski  and @evil-at-wow in this old and dusty place. We should throw a party here, from time to time.

I'm trying to fix or at least improve the SD2 script of Ragnaros and for this purpose, I'd like your help. By any chance, do you have data (mainly spawn points and related spells) of GO 178088 (Ragnaros), please. Yes, this is a GO with the same name as of the NPC.

**Comment by Tobschinski** [comment]
I had [this](http://pastebin.com/PStDkCqg)  file with the name 'lava burst ragnaros' on my desktop, is that what you want? They cast spell 21158.

**Comment by cala** [comment]
I have no other choice than to bow before your might, O Great One. 🙇

**Comment by Tobschinski** [comment]
Sons aren't randomly spawned either, most likely summoned by spell 21108, which casts 20110-21117.

**Comment by cala** [comment]
Yes, there is a spell with specific coordinates for each Son of Flame and also for each Lava Burst GO. So, definitely, that indicates that spawn points are fixed and not random. Unfortunately, those spells were removed in TBC and later. So, I think I will readd the spells in TBC and later and put the coordinates in `spell_target_position` and trigger the spells in SD2 instead of the actual random summons.

Could I request more data from you, please ?
Like spawn coordinates of the 8 Son of Flame and if you have a timeline about the Lava Bursts. Do they spawn all at the same time (on the same timer) or do they spawn one at a time, each on its own timer or a shared trigger that spawn one Lava Burst randomly ?

**Comment by cala** [comment]
> Do they spawn all at the same time (on the same timer) or do they spawn one at a time, each on its own timer or a shared trigger that spawn one Lava Burst randomly ?

Looking at the spells, I found a partial answer with spell 21908 (Lava Burst Randomizer). So, I guess that this spell is on a timer and that it randomly pick one of the spells from 21886 to 21907 to spawn one of the lava burst GO. So, I would only need some timer for the lava burst GOs spawning.

**Comment by cala** [comment]
Some videos show a timer ranging from 14 seconds to 35 seconds (and possibly 45 seconds) for lava burst.

**Comment by Tobschinski** [comment]
I want to double check that first, 1k damage on a 15-35s timer for 40 guys sounds a bit under-tuned, maybe there's more than just one GO spawned. I'll see ...

**Comment by cala** [comment]
I agree, but keep in mind that this is not is primary attack and has a random part, so we should not expect too high damage either.

**Comment by Tobschinski** [comment]
I see these GOs spawning with only 2 (!) seconds in between, then again, sometimes nothing for 10 seconds. I'll do some more tests, but don't wait for me, I need at least a week before I can do that. It's just a timer, very easy to change after the work is done.

**Comment by evil-at-wow** [comment]
I don't think I have a lot of relevant data. I've only killed Ragnaros a handful of times in MC, and that was mostly at level 85 (soloing Molten Core at level 80 was rather time consuming so I usually just went to kill the bosses that dropped the Bindings). But at level 85 he was dead before he could even realize I was there, so I don't think I'll get any useful timer info out of that...

I could most likely get a few spawn positions, but it looks like you already have those. Is there anything else still missing completely?

> We should throw a party here, from time to time.

As a destro warlock, I disagree (even though the problem that literally everything in there is immune to almost all your spells is gone nowadays). Let's just go party in Scholomance instead!

**Comment by cala** [comment]
> Is there anything else still missing completely?

The spawn points of the eight Sons of Flame. In current core, they are randomly spawned but @Tobschinski and I are pretty sure their spawn points are static on retail. 

And I agree with a party in Scholomance. :)

**Comment by evil-at-wow** [comment]
It looks like I can help with those. I had a quick look in my archives and found (only) two cases where Ragnaros lived long enough to hide for a moment. The good news is that the two sets of data seem to confirm your idea that the spawn positions are static.

A sniff from version 3.3.0a build 11159 results in these spawn positions (I didn't verify any of these ingame, so I hope I'm copying the data of the correct NPC):

| x | y | z | o
|---|---|---|---
| 811.448 | -814.058 | -233.177 | 0 |
| 842.542 | -797.822 | -233.34 | 0 |
| 870.668 | -821.862 | -232.938 | 0 |
| 874.851 | -861.112 | -232.336 | 0 |
| 891.442 | -789.678 | -232.801 | 0 |
| 824.827 | -871.046 | -232.421 | 0 |
| 818.517 | -898.278 | -232.903 | 0 |

These 7 spawn positions match exactly with the second sniff (version 3.3.5a build 12340), so I'm fairly confident they are correct. 

There is of course one additional 8th position, but this is where both sets of data disagree, and for a reason I think. It is worth mentioning that spawn position number eight was *not* sent in the same server packet but in the next packet (data set 1) or a few packets later (data set 2). My theory about this is that this spawn is furthest away and was too far away from my character, unlike the seven other spawns (but as mentioned before I didn't check where those coordinates end up ingame). I think the one from data set 1 is reasonably trustworthy, given that a) it was sent in the next server packet (meaning immediately after the other spawns) and b) has orientation 0, just like the other spawn points. So perhaps this one was just at the distance limit of being sent to my character, and I just slightly moved or something while Ragnaros was hiding and the server was spawning the adds. I don't know why the server didn't add that one in the same packet as the others. In data set 2 however, the spawn was sent a few packets later, so I'm guessing the add already started to move, and therefore has a non zero orientation. Don't trust this one, but the fact it's very close to the point of set 1 also confirms the static nature of the spawn.

| x | y | z | o| comment
|---|---|---|---|---|
| 868.206 | -895.036 | -233.1 | 0 | Set 1
| 867.094 | -859.226 | -231.326 | 2.04325 | Set 2

Personally I'd just go with the first point here as if it was correct, and totally ignore the second one. But I wanted to share the entire story with you, so you can judge for yourself.

Sadly I don't seem to have more than those two sets of data with Son of Flame spawns, so that's the best I can do.

**Comment by cala** [comment]
@evil-at-wow thank you very much ! I agree with your analysis of the eighth spawn point and I have rewritten the summoning part of the Ragnaros SD2 script accordingly.

Yesterday, I managed to have a fully working Lava Burst ability and now that I have a whole understanding of the spell mechanics, I know that I can't rely on a video to guess the timer: only spawn time of GO 178088 are relevant. So @Tobschinski is probably right on this.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/1448202287692bd1abe8667cb5f5db18e39750bd and previous core/DB updates.

**Comment by cala** [comment]
@Tobschinski @evil-at-wow you know me, I can not stop myself. While reviewing again Molten Core in cmangos, I noticed the fire runes are not fine (those used to summon Majordomo Executus).

Currently, they do stop burning when doused with the quintessence. But the circle of flames around them is still here. Moreover, when reloading the instance, the rune is burning again (while the instance data counts it as doused).

From what I remember/see in videos, the circle of flames around a rune should disappear when the related boss is defeated. Then, the players can douse the rune. When instance is reloaded, the circle and rune should remain disabled.

I would like to add this behaviour in current cmangos (work already started) but before that, I need more data about how things work, more precisely, how the circle of flames works.

By any chance, do you have data about go 176957 (Rune of Mohn) and its related circle (178193 - Molten Core Circle GEHENNAS). I'd like to know more about those two GOs and what happens when Gehennas (12259) is defeated and when the rune is doused. Please. :)

**Comment by cala** [comment]
I just want to add that apparently, the behaviour I described was valid until patch 3.0.8. From that point, the circle AND the rune are automatically desactivated when the boss is defeated.

I'm still interested in what happens to the circle of flames.

**Comment by Tobschinski** [comment]
I remember it like you do, the circles should de-spawn when you kill the linked bosses. The runes have to be doused manually. But I do not have data old enough to back it up.

**Comment by cala** [comment]
What puzzles me with the circles **as they currently are in the DB**, is that they are trap gameobjects and that the rune, when doused, activates that trap.

It makes sense for WotLK :  if the rune is automatically activated by script on boss death, it will also trigger the trap: both are supposed to be activated on boss death.
But for TBC and Classic, it makes no sense for the circles to be trap GOs, buttons GOs (like the runes are) would be a much better choice.
I'm starting to consider changing the type of those GO for Classic and TBC, but I would like something to backup this first...

**Comment by cala** [comment]
It appears the current DB state for those GOs were already that way in 2006... Weird.

**Comment by evil-at-wow** [comment]
I don't have old MC data either, so at best I can check what early WoTLK data reveals. Time allowing, I'll see what I can do for you next weekend.

But I remember reading an article or blog - related to WoW's 10 year anniversary and the MC special they did? - were one of the designers mentioned something like the original MC having a pack of 'dummy' Rats in the instance because spells could only target NPCs back then and so they added some Rats that served as targets for whatever. I wonder if this could be related.

[edit]
I found what I was looking for: if you go to [this post](https://worldofwarcraft.com/en-us/news/13936505) and hover over 'Majordomo Executus' you get to see some additional text:

> Indestructible Rats
> Sometimes the devs needed to get creative to make certain effects possible. Triggers needed to be placed in the dungeon for each of the runes that would activate when a boss was killed. For a trigger to exist, it had to be attached to an NPC, so each of those triggers was an indestructible rat that sat on the rocks behind where Baron Gedden roams..

**Comment by evil-at-wow** [comment]
I took some time to take a quick look and was able to find the GOs in early WoTLK data (version 3.0.8, build 9506).

Gameobject: GUID = 0xf11002b33d0000e3  Entry = 176957/0x2b33d (Rune of Mohn)
Gameobject Type = 1  DisplayID = 2773
Position (x y z o) = (897.058 -551.546 -203.953 3.14159)

Gameobject: GUID = 0xf11002b8110000e4  Entry = 178193/0x2b811 (Molten Core Circle GEHENNAS)
Gameobject Type = 6  DisplayID = 410
Position (x y z o) = (897.058 -551.546 -203.953 3.14159)

The associated SMSG_GAMEOBJECT_QUERY_RESPONSE packets that contain the data0-data23 fields are below:
```
00000000:00000000 | 3d b3 02 00 01 00 00 00 d5 0a 00 00 52 75 6e 65 | =...........Rune | 
00000000:00000010 | 20 6f 66 20 4d 6f 68 6e 00 00 00 00 00 00 00 01 |  of Mohn........ | 
00000000:00000020 | 00 00 00 b3 05 00 00 00 00 00 00 11 b8 02 00 00 | ................ | 
00000000:00000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000040 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 | ...............@ | 
00000000:00000080 | d9 84 3f                                        | ..?              | 
```

Type = 1 (Button)
Data0 = 0x00000001 = 1
Data1 = 0x000005b3 = 1459
Data3 = 0x0002b811 = 178193 (Molten Core Circle GEHENNAS)
The others are 0.

```
00000000:00000000 | 11 b8 02 00 06 00 00 00 9a 01 00 00 4d 6f 6c 74 | ............Molt | 
00000000:00000010 | 65 6e 20 43 6f 72 65 20 43 69 72 63 6c 65 20 47 | en Core Circle G | 
00000000:00000020 | 45 48 45 4e 4e 41 53 00 00 00 00 00 00 00 00 00 | EHENNAS......... | 
00000000:00000030 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 | ................ | 
00000000:00000040 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000050 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000060 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000070 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000080 | 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 | ................ | 
00000000:00000090 | 80 3f                                           | .?               | 
```

Type = 6 (Trap)
Data4 = 0x00000001 = 1
The others are 0.

I also did a quick search with those GUIDs in the hope I would see something's happening to them, but I haven't found anything so far. But obviously something should be there because there's an effect in game. Sadly my tools don't allow me to search for events like "Gehennas dies", so I guess I'll have to dig a bit further (semi-)manually later.

**Comment by evil-at-wow** [comment]
And I have found a few things related to the GOs. Just after Gehennas' death, the Rune is involved in a handful of SMSG_COMPRESSED_UPDATE_OBJECT packets that update some of the GOs fields. In order:

SMSG_COMPRESSED_UPDATE_OBJECT:
Packed GUID = 0xf11002b33d0000e3
  Update field 9 = 0x00006400 [GAMEOBJECT_FLAGS]
  Update field 23 = 0x01010000 [GAMEOBJECT_BYTES_1]

SMSG_COMPRESSED_UPDATE_OBJECT:
Packed GUID = 0xf11002b33d0000e3
  Update field 9 = 0x10006400 [GAMEOBJECT_FLAGS]

SMSG_COMPRESSED_UPDATE_OBJECT:
Packed GUID = 0xf11002b33d0000e3
  Update field 20 = 0x00006400 [GAMEOBJECT_DYNAMIC]

The circle GO surfaces in two packets that are sent together:
SMSG_GAMEOBJECT_DESPAWN_ANIM + SMSG_DESTROY_OBJECT
GUID = 0xf11002b8110000e4

I can't guarantee that's everything for these GOs, but so far it looks like some stuff is going on to update the Rune GO, and then the Circle GO is despawned?

**Comment by cala** [comment]
Wow. Being able to get all those data on request, you are more of a wizard than a warlock ! Unless... unless you got them by dark means, involving the sacrifice of some innocent being in order to rip its souls out of its body as a currency to buy those data. In such extends, you are indeed an evil warlock...

Anyway, who am I to wonder about the source of such data? I'm just an old turtle who only cares about swimming and laying down eggs.

Thanks for all those data. I'll see how I can put them to a nice script. 👍 

MC is almost cleansed, I'm merely missing the data about the Ragnaros submerge part, but @Tobschinski told me on IRC he should be able to get them.

**Comment by Tobschinski** [comment]
I wouldn't trust THAT loser if I were you

**Comment by Tobschinski** [comment]
Not a lot I can give you. The only spell I could see was 20567. But that could do anything ...

**Comment by cala** [comment]
This is the original visual spell used by Ragnaros that applies a dummy aura. This means that the effects added in later patches are probably handled in the dummy aura. I have yet to found out how to properly implement them...
So yes, this info is usefull to me! 👍

**Comment by cala** [comment]
The runes are scripted correctly in SD2 now. I give up on the Ragnaros submerge visual. I can't manage to have it working.

**Comment by Tobschinski** [comment]
It does not? Seems to work just fine for me ...
