### ISSUE TITLE
Couple minor Blacksmithing bugs

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#268]
journeyman blacksmith in Stormwind doesn't teach Rough Grinding stone which is at skill level 45 but teaches up to skill level 75, only the expert blacksmith teaches it.

---

Artisan Blacksmith in Ironforge only teaches up to a skill level of 225 but has 2 recipes for 230 which you can't learn from him.

**Comment by cala** [comment]
Thanks for this report.

Dane Lindgren, Journeyman Blacksmith did teach skills up to level 75:
source: http://www.wowwiki.com/Dane_Lindgren?oldid=477428
However, Rough Grinding Stone recipe plan is indeed missing.

Regarding Bengus Deepforge, can you point to a reliable source indicating that he shouldn't have these two lvl 230 blacksmithing plans, please? Because I do remember trainers that sold a few skills above their training level (while most of the higher levels skills were indeed sold by higher trainers). It was probably to help the transition from one trainer to another.

**Comment by scotty0100** [comment]
I remember that too - but I thought they sold the recipes as opposed to actually training them.

Don't have a reliable source yet.

**Comment by cala** [comment]
As far as I remember, recipes/plans and such were:
- sold by merchants, especially "Alchemy/Blacksmithing/Tailoring/... Supplies" vendors for the common quality recipes/plans
- dropped by NPC for uncommon quality and above
- quest reward for a few ones

But I think trainers only, well, trained.

As such, I will let Bengus untouched for now and only fix Dane Lindgren. But if you find source, I'll gladly update Bengus also. :)
