### ISSUE TITLE
Wailing Caverns   the end Event don't start 

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#282]
In The "Wailing Caverns"  the End Event with NPC ID 5767  Nalpak Disciple of Naralex   don't work,
i think it is the  quest ID 1500 but i'm not sure

**Comment by cala** [comment]
I must admit I never test it with cmangos (only retail), so I have no clue:
- if it should be working
- if this is a DB or script issue

**Comment by Neotmiren** [comment]
Tested and seemingly fixed it for my build (may differ somewhat from current CMangos) just now.

Event starts after 4 fanglords of WC are slain. But Disciple of Naralex (tauren) even does not show no gossip text saying about this condtion due to very bad idea of removing data `npc_gossip` table before modifying core. Can be fixed by

INSERT IGNORE npc_gossip SET npc_guid=(SELECT guid FROM creature WHERE id=3678 LIMIT 1), textid=698;

And then there is ScriptDev2 error (someone really tries to program without testing) in DoSpawnMob() that causes creatures to despawn before they defeated by players. This leads script to stuck in waiting for "all summoned creatures are slain" condition (Mutanus the Devourer never summoned, Naralex never awakened). Can be fixed by something like

m_creature->SummonCreature(uiEntry, fX, fY, fZ, 0, TEMPSUMMON_CORPSE_TIMED_DESPAWN, 120000);

And after all, Disciple of Naralex and Naralex himself transformed into owls, started to fly away, but unhappily attacked by enemies on their way and began to fight. Naralex despawned after some time, but his tauren disciple remained in the location of combat after enemies were defeated.

**Comment by evil-at-wow** [comment]
I haven't tested this recently, but this worked more or less about two years ago on my TBC server (TBC-DB). I assume the Classic and TBC versions of the core and SD2 are similar enough and won't cause any relevant differences, but perhaps you can grab some useful data from TBC-DB. Starting the event worked fine and the escorting part worked fine too - although you had to be careful along the way because the Disciple of Naralex was neutral and could be attacked by accident (for instance with your AoE spells). It was the waking event that often went wrong, because of what seems to be a core issue (or two even). One is described [here](https://github.com/scriptdev2/scriptdev2/issues/16). Unfortunately I can't link to the second issue as described in detail in my analysis of the issue because it was posted on the SD2 forum and the forum is still down...

**Comment by cala** [comment]
Tested and working. I'm closing the issue. Thanks everyone.
