### ISSUE TITLE
Quest ID 6621  King of the Foulweald  

### ISSUE THREAD

**Issue by Dainara82** [classicdb/database#284]
i don't know what exactly happen, but a friend tell me, that he played with an other player

the Item ID 16976  got only one pkayer
and the quest don't be finished at the end

**Comment by Tobschinski** [comment]
My thoughts about this quest.

Remove item 16976 from NPC 12918.

You should only get it if you open the spawned GO 178227. TO was correct, only one player can loot it for now. I don't know how to change that, but it should be done.

In order to complete the quest, you need to hand in the banner as well, which you previously destroyed by putting it into the ground. 

A temporary solution: Drop the quest and retake it. You won't lose your totem (which you should) and get a new banner to hand in both.

Taken from wowhead, the banner has a 2 minute cooldown. But I do not know if this was the case in vanilla.

The quest itself would need some rework too, the NPCs should start walking towards the hill and attack the player on their own. If no player is attackable, they should start hitting (and finally destroying) the placed banner.

Also, make sure only one event can be started at the same time. 

Last but not least, remove a strange looking apple with a strange looking tooltip from there.

**Comment by TheTrueAnimal** [comment]
There also seem to be too many NPCs. It should be 6-10 until the boss spawns. I've been waiting on the hill until all were spawed (easy because they don't attack you) and counted 18 NPCs.

https://web.archive.org/web/20070629130555/http://thottbot.com/q6621
http://www.wowhead.com/quest=6621/king-of-the-foulweald
http://wow.gamepedia.com/Quest:King_of_the_Foulweald
https://www.youtube.com/watch?v=qjpqeP9vo5U

**Comment by cala** [comment]
There was a commit by our friends from Trinity Core about this. 
I put it here for reference: https://github.com/TrinityCore/TrinityCore/commit/644b9dcd59252e677639ccca6fb4048ee6e4bf44

**Comment by Lumber-Jack-2** [comment]
the only problem with this script is a LOS issue (the creatures run directly IN the gameobject)

**Comment by Kittnz** [comment]
So this is a core issue?

**Comment by Lumber-Jack-2** [comment]
it's more like a missing feature
the creatures should only run _close_ to the gameobject, but not directly IN the banner
movepoint() was the only function i could find so far in sai and corescript for handling the movement

**Comment by cala** [comment]
Will now be followed in https://github.com/cmangos/classic-db/issues/44
