### ISSUE TITLE
[NPC] Andorgos - missing teleports

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#375]
[Andorgos](http://wowhead.com/npc=15502) is missing his (Yes, 'his', I don't know why a male dragon dresses like a female gnome, but he does) options to teleport players after certain encounters have been defeated.

**Comment by Tobschinski** [comment]
I have added them, but I was unable to add conditions. The only condition-types that would come to my mind are `CONDITION_COMPLETED_ENCOUNTER`, which seems to not be useable, due to missing Encounter.dbc and `CONDITION_INSTANCE_SCRIPT`, but I wasn't able to find any useful information there either.

Can this be currently done?

EDIT: Regarding wowpedia.org, the conditions for 'Teleport Final Chamber' are far worse ...
"Andorgos will teleport you to the Twin Emperors' chamber once they have been defeated, or to C'Thun's chamber after you first encounter him."

Tomorrow, I will be able to test, if I am able to teleport to C'Thun after just defeating Ouro.

**Comment by cala** [comment]
Those gossips should have been backported in rev 0062 but as you noticed, the core does not support the encounter done conditions for Classic. We chose to keep them out until core is updated.

Baron Aquanis in Blackfathom Deeps also requires an encounter done check that is missing. Before SD2 forums went down, we discussed there with @schmoozerd to move Encounters.dbc to the database in order to allow Classic corr to also use this feature, but the discussion did not had the opportunity to go further.

**Comment by Tobschinski** [comment]
Are there any other needed encounter-checks for classic besides these two mentioned here? 
If not I'll try to add them with SD2 on encounter==done for Twins and !encounter==not_started for C'Thun. That'll be less work, imho.

**Comment by cala** [comment]
I think there is no other cases for Classic at least.
But we discussed recently with Schmoozerd and Xfurry to do the above mentioned core update and I'll do it when I can spare the time.
So the SD2 update will not be needed because once the core is updated to handle Encounters from database, the encounter status will be accessible via conditions and as such, DB-scripts and gossips. Thank you for the proposal, anyway. :)

**Comment by Schmoozerd** [comment]
also keep in mind that there are similar issues introduced with tbc - so a db-solution is likely better choice.
