### ISSUE TITLE
Blackrock Depths Vault: Dark Keepers & Heart of the Mountain Quest.

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#380]
#155 Update on this: (Probably can close that bug report I referenced as that part of it does actually work now.)

With the most recent Classic DB Core / SD2 / Acid this works but there's still some bugs involved with it.

The Relic Coffers aren't intractable . The Dark Coffer also aren't intractable, as well as the Secret Safe.

The Dark Keeper Nameplate also doesn't work.

And also when Watchman Doomgrill spawns he should yell:

"What are you doing? Intruders!!"

It should work something similar to this: 

https://www.youtube.com/watch?v=vQ7-17CS1y4

The following SQL will make all the items usable, as they all had flags of 16 (which isn't usable)

UPDATE gameobject_template SET flags = "0" WHERE entry = '164825'; /\* Dark Keeper Name Plate */

UPDATE gameobject_template SET flags = "0" WHERE entry = '160836'; /\* Relic Coffer */

UPDATE gameobject_template SET flags = "0" WHERE entry = '160845'; /\* Dark Coffer */

UPDATE gameobject_template SET flags = "0" WHERE entry = '161495'; /\* Secret Safe */

After running this SQL; all chests are now lootable with loot tables although when reading the Dark Keeper Name Plate, the Dark Keeper doesn't actually spawn making the Dark Coffer unattainable.

And also for the quest Heart of the Mountain, it doesn't seem to appear after beating Watchman Doomgrip.

http://db.valkyrie-wow.com/?quest=4123

**Comment by scotty0100** [comment]
On further testing, removing the flag 16 of not usable opens it up to an 'exploit' you can interact with all the objects through the walls. Without needing any keys..

So perhaps another way around that is needed.

**Comment by cala** [comment]
@scotty0100 
The issues in #155 were:

> Relic Coffer in Blackrock Depths doesn't Work
> Gameobject ID : 160836
> 
> You open the door with item 11078 = work
> You try to open relic coffer (gameobject 160836) = no interaction icon
> 
> When you have open all the coffers, the golems don't pop.

From what you are saying (I did not test):
- Relic coffer works now
- when opening the coffers, the golems attack

If this is so, I can close #155 and look at the current issue.

**Comment by scotty0100** [comment]
That's right. Just need to look at when looking at Dark Keeper Nameplate, it should spawn a random Dark Keeper somewhere. Possibly need a script so that once a Relic Coffer is opened the Relic Coffer chest relevant to that door ID becomes flag 0.

**Comment by evil-at-wow** [comment]
The BRD vault was on my list too. I have sniffs with all possible Dark Keepers, so I should be able to get their data and position (and waypoints for the group that spawns in the vault itself). So no need to guess the positions with a video or something. I just need to parse them some day and add them...

**Comment by cala** [comment]
@evil-at-wow thanks, I would appreciate the data about the dark keepers if you can spend some time on this. As you might be guessing, I'm working on BRD now. :)

**Comment by evil-at-wow** [comment]
@cala You know I'd do everything to support perfection - data incoming! 

Per group that spawns together:

| Entry | Name | x | y | z | o |
| --- | --- | --- | --- | --- | --- |
| 9437 | Dark Keeper Vorfalk | 815.276 | -168.652 | -49.6699 | 6.23083 |
| 9445 | Dark Guard | 816.276 | -167.652 | -49.6699 | 5.58505 |
| 9445 | Dark Guard | 817.276 | -166.652 | -49.6699 | 4.88692 |
| --- | --- | --- | --- | --- | --- |
| 9439 | Dark Keeper Uggel | 901.537 | -359.291 | -49.908 | 3.31613 |
| 9445 | Dark Guard | 903.295 | -356.783 | -49.8522 | 3.68264 |
| 9445 | Dark Guard | 902.896 | -361.966 | -50.0812 | 2.74017 |
| --- | --- | --- | --- | --- | --- |
| 9441 | Dark Keeper Zimrel | 549.701 | -214.474 | -36.8893 | 0.331613 |
| 9445 | Dark Guard | 549.796 | -217.958 | -36.8654 | 0.890118 |
| 9445 | Dark Guard | 548.083 | -212.932 | -36.8628 | 6.26573 |
| --- | --- | --- | --- | --- | --- |
| 9442 | Dark Keeper Ofgut | 679.491 | -7.79026 | -59.9754 | 1.8326 |
| 9445 | Dark Guard | 680.491 | -6.79026 | -59.9754 | 2.18166 |
| 9445 | Dark Guard | 681.491 | -5.79026 | -59.9754 | 2.58309 |
| --- | --- | --- | --- | --- | --- |
| 9443 | Dark Keeper Pelver | 802.755 | -245.25 | -43.2198 | 2.93215 |
| 9445 | Dark Guard | 805.289 | -243.172 | -43.2198 | 3.42085 |
| 9445 | Dark Guard | 801.935 | -248.841 | -43.2198 | 1.95477 |
| --- | --- | --- | --- | --- | --- |
| 9438 | Dark Keeper Bethek | 862.461 | -309.724 | -49.8757 | 3.85883 |
| 9445 | Dark Guard | 863.219 | -305.041 | -49.8751 | 3.68264 |
| 9445 | Dark Guard | 860.947 | -302.54 | -49.8787 | 4.04916 |
| 9445 | Dark Guard | 864.232 | -303.735 | -49.8527 | 3.735 |
| 9445 | Dark Guard | 862.676 | -301.922 | -49.8527 | 3.9619 |

All groups are completely static (= not even random movement), except the last one with Dark Keeper Bethek, which uses waypoints. Analyzing all movement data of that group over several minutes shows that Dark Keeper Bethek is the only one with a nicely repeating pattern. His Dark Guards don't have any exactly repeating pattern; their position varies slightly between tours and they update their movement far more frequently than Bethek. Or in other words: unsurprisingly, Dark Keeper Bethek is the group leader and the Dark Guards are not using own waypoints but run in formation based on Bethek's position.

Waypoints for Dark Keeper Bethek (in this order):

| Point | x | y | z | o |
| --- | --- | --- | --- | --- |
| 1 | 855.505 | -309.724 | -50.1398 | - |
| 2 | 847.214 | -316.912 | -50.2843 | - |
| 3 | 842.652 | -321.334 | -50.2848 | - |
| 4 | 839.316 | -324.232 | -50.6638 | - |
| 5 | 833.983 | -329.089 | -50.6638 | - |
| 6 | 822.84 | -339.999 | -50.1851 | - |
| 7 | 810.483 | -350.225 | -50.5781 | - |
| 8 | 806.646 | -353.272 | -50.1957 | - |
| 9 | - | - | - | 0.715585 |

I assume the NPCs entries above are known in the database, but if that's not the case, just shout and I'll go fetch those packets for you!
Also, I haven't verified any positions ingame, but I trust my tools. And I'm sure you will check out the final results anyway. :smile:

**Comment by Tobschinski** [comment]
Hah, they did not even move Dark Keeper Belvet, although there is an enormous mole machine in his back nowadays.

**Comment by Tobschinski** [comment]
@evil-at-wow I have edited the waypoints table, if you don't mind.

**Comment by evil-at-wow** [comment]
Hmm. I think I can see now why you've done that edit - the duplicate row. There's something weird going on here... because that duplicate row is actually there in my sniffs and not just once but every cycle! I agree that wasn't clear because I didn't include the timing info I see here. In fact, the client is sent that very same waypoint again with a delay between 2.8 and 4.5 seconds (but note that this is just an observation on my side when tapping the wires; the real server side values could be a nice interval for all we know). Without further checking the coordinates, but knowing the group patrols inside the vault from one side to another, I can only guess this is at one of the two endpoints and the seemingly random delay is just the group pausing for a short while, before returning and doing another cycle.

The question here is if I'm somehow missing a point between those two, or if the offi servers actually send it again, to sort of reset the cycle?

If it's the end of a cycle, I agree that it makes sense to have this waypoint as last one in the list, but that is NOT correct according to my tools: they insist that after the spawn, the very first 'monster move' packet that gets sent to the client contains (847.214, -316.912, -50.2843), and not the point you have put at position 1 now! But maybe my tools are just buggy... 

Also, could you explain what the point is (pun intended) of that last row with just an orientation? I'm guessing you want a correct orientation at the end point, but I'm missing the how with a row like this?

For reference purposes during the discussion, I believe this is what the table looked like before the edit (I had to search this in my archives again and reparse because I wasn't sure any more what the original was), with points 8 and 9 the duplicates/weird situation:

| Point | x | y | z |
| --- | --- | --- | --- |
| 1 | 847.214 | -316.912 | -50.2843 |
| 2 | 842.652 | -321.334 | -50.2848 |
| 3 | 839.316 | -324.232 | -50.6638 |
| 4 | 833.983 | -329.089 | -50.6638 |
| 5 | 822.84 | -339.999 | -50.1851 |
| 6 | 810.483 | -350.225 | -50.5781 |
| 7 | 806.646 | -353.272 | -50.1957 |
| 8 | 806.646 | -353.272 | -50.1957 |
| 9 | 855.505 | -309.724 | -50.1398 |

**Comment by Tobschinski** [comment]
Did you look at the initial SMSG_UPDATE_OBJECT? Because there first WP (or current) is sent there, afaik. It would look weird if this information would be split among different packages. The creature would not move for a short amount of time.

About the duplicate row, Blizzard use the SMSG_MONSTER_MOVE package to either send a new XYZ point, or an orientation O, but never both. I observe this quite often. Do you have an orientation sent in package 8? Because I have ... 0.715585
