### ISSUE TITLE
Vekniss Drone - Mining-Emote

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#405]
Currently, I am trying to rework the 'suppression room' in AQ40. Some (just the ones to the sides) drones use the mining emote (ID28) for half of a minute and then stop for 15 seconds.

Adding a permanent emote can be done with creature_addon. But how do I realize the described situation above?

I would love if someone could help me out. Thanks in advance!

**Comment by cala** [comment]
This is typically the kind of stuff handled by ACID. 
See: https://github.com/cmangos/issues/wiki/creature_ai_scripts
ACID repository is: https://github.com/scriptdev2/acid but we can discuss this here and push it to ACID later

Since, you are working on the bug corridor, could you also add two entries in `creature_linking_template` to prevent the creatures to respawn once Fankriss is killed, please? I already took care of the respawn time of those NPCs a week ago.

**Comment by Tobschinski** [comment]
Yep, no worries about the linking. 
Do you have the same info for respawn as I do? 25 seconds for most of the Drones, 10-15 minutes for Soldiers (I used 10 here) and 10 minutes for a few Drones that will respawn even if Fankriss is dead and 10 minutes for Drones that are patrolling. (I thought of adding a creature_linking with flag 0 to override the template for the respawning ones)

BTT: Isn't ACID used to add behavior for ALL creatures of this type? Because I only want to add it to some of them.

As this is related to guids, I'd assume it is hard to impossible to sync it with a independent project like ACID. 

I thought of adding waypoints with no positioning change for them and make them use their makro on WP1, but if I do that, they will remain still on WP2 and do not use their random animation (I do not know how to describe that, mobs that are standing still turn left and right to make them look better)

**Comment by cala** [comment]
For the respawn time, it was done in: https://github.com/classicdb/database/commit/ae538d34564eed566713dcd88001bdd42d1a9ec9 and was set to 20 secs for both Drones and Soldiers. wowwiki was suggesting that they have the same respawn time. But after digging a bit more, it looks like soldiers have a longer time. So my commit needs to be updated if we are sure of this.

Regarding the different spawn time, this is easy to handle with `creature.spawntimesecs` but the different linking behaviour is another matter... I'm afraid adding them to creature_linking with FLAG = 0 will raise an error message instead of overriding the template.

Yes, ACID is for every creature with the same ID. For the behaviour you are suggesting, you should use `dbscripts_on_creature_movement` between two waypoints located at the same place (use a very small change of orientation to make sure the core processes them) and use the waittime to define how long the NPC stays in a state.
You can have an example with this commit: https://github.com/classicdb/database/commit/7e126c1b2621bc3de39c483b895cb7dc334081eb
You can use SCRIPT_COMMAND_MOVEMENT to toggle the waypoint/random movement for the creature and assign a very short roaming range (1 for example).

**Comment by Tobschinski** [comment]
Oh yeah, damn. The loadup-corrections! 

Maybe I can convince someone to give us some kind of dummy flag for that. It will definitely lower the needed entries. But I don't know if this would match the standards.

Getting the correct respawn timers would be easier if not every single website or guide would use different values T_T.
15, 20, 25, 30 - got them all.

The exact ones for the live servers are 25s for the drones to the sides, 25s for the ones in the middle, 10m for the ones between the middle groups + pats and 10-15m for the soldiers.
Up to you what makes it into the DB.

And thank you very much for your given information, I will take study it.

**Comment by cala** [comment]
> Up to you what makes it into the DB.

On _this_ matter, I will trust retail value over some web sites, especially as those values are not caught by the addons, but estimated by players.

Regarding the different respawn times, maybe we can do this by SD2 also: spawning the new NPCs with longer respawn time only once Fankriss is defeated.

**Comment by Tobschinski** [comment]
Oh, not needed. The respawn times are not related to Fankriss. Even with him being alive, pats and some Drones do respawn after 10 minutes, unlike the rest.

Anyways, I have given you the option to easily change arguable values and set my proposed ones for now.

**Comment by Schmoozerd** [comment]
personally i don't like the idea of "unlinking" some npcs via guids from the generic linking by template.
Maybe - as this is probably a rather unique issue - an SD2 solution is in order, and their respawn-time can be modified depending on status of the instance data.

**Comment by cala** [comment]
Closed by https://github.com/classicdb/database/commit/e817dd721b9d12d6e24098a5fb9c03b6f55c2567
The linking issue wil be moved from DB.
