### ISSUE TITLE
[The Scepter of the Shifting Sands] quest chain

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#407]
Signet Ring of the Bronze Dragonflight:
The Qiraji Conqueror - is broken.
The Changing of Paths - Conqueror No More - is broken.
The Grand Invoker - is broken.
The Changing of Paths - Invoker No More - is broken.
The Protector of Kalimdor - is broken.
The Changing of Paths - Protector No More - is broken.

Explane: http://www.wowwiki.com/Quest:The_Changing_of_Paths_-_Invoker_No_More

 You need to gather each of those items + the ring to complete the specific quest. But atm Anachronos just gives you the rings for free.

Long Forgotten Memories quest is partly broken. When you wanna complete the quest (as shown in video) at Crystalline Tear, it does nothing.

 Long Forgotten Memories quest reference: https://www.youtube.com/watch?v=LspLWzA3qy0

The Charge of the Dragonflights - Anachronos does not give you the quest.

**Comment by Tobschinski** [comment]
on my list, if no one is quicker than me ...

**Comment by cala** [comment]
I did no check the rings quests, however the Long Forgotten Memories quest line is working as intended. You have to do it the right way: take the quest from Anachronos with GM off. If you use any "GM trick", it won't give you completion credit.

So Long Forgotten Memories -> A Pawn on the Eternal Board -> The Charge of the Dragonflights : OK

**Comment by Metalica** [comment]
If you use any "GM trick", it won't give you completion credit.

 Tried that it work, tnx. Other part's are broken.

**Comment by Tobschinski** [comment]
I have an open PR [here](https://github.com/classicdb/database/pull/419)

Unfortunately, it does not fix all mentioned issues, because the core would need to be updated first.

**Any of the 3 final quests of your chosen path should unlock all 3 repeatable quests to undo your choice.** 
Regarding the wiki, this is currently not possible.

Maybe I / we can get some information from @Schmoozerd, why this is technically not possible, if he / you has / have the time for it, would be much appreciated. :)

In addition, I still need some legit data for the reputation gain for all of these ring-quests. wowhead states 250, live servers 135 and so on ... I really need to find a classy value.

**Comment by Schmoozerd** [comment]
technically you have four fields to group quests:
PrevQuest, NextQuest, ExclusiveGroup, NextQuestInChain
all these four can have positive or negative values.

You can read the wiki documentation carefully, maybe there is a combination remaining open than can be used for such a case.

Other attempts for this would be to use an SD2-hook for quests and handle these rare cases manually.
Or to add a condition_id field to quest_template so that additional requirements for a quest can be toggled via conditions.

But of course any such change will require some checking of code, to see ie when/how/ if some updateing of available quests will be required.
In general adding condition_id is nicest and cleanest,but you must be aware of requirements to the code (compare to commits https://github.com/cmangos/mangos-wotlk/commit/ef5e75ae25891e602d07277ab4bd22d5720a1eba https://github.com/cmangos/mangos-wotlk/commit/e91ad73e0a68923bb84d4d17ccfc95abc482403b )

The difficulty is to update quest-visibilities in case of status changes in some conditions - which sort of is not possible..

Edit: It is very likely that for all real-game cases having no callback from condition-change to quest availability is no problem.

To clarify what i mean with callback of condition-change.
Assume QuestX can only be started when a player has items A & B in his inventory.

Real-Game Example would be QuestGiver GX for X resides somewhere far far away from where items A&B can be obtained. So when a player with these two items travels to GX he will get the proper status of the quest (yellow !) based on his inventory.

But theoretical Example would be: Player is near GX, but does not have A&B in his inventory, so he gets GX without the ! (so far so good).
But then the Player gets A & B directly (like with gm cheating), so now Player has A&B, but GX has not been updated (no !) - so no more good.

**Comment by Tobschinski** [comment]
Oh, this looks like a massive rework for such little benefits. Thanks sharing your thoughts. I will move it to the issue tracker and link this thread to not lose them.

It's a pity I am not capable of doing things like these on my own.
