### ISSUE TITLE
LBRS / Finding Vaelan

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#411]
Vaelan does not work properly:
- Skill that he uses: mind probe / 16037
  
  Youtube link for reference: https://www.youtube.com/watch?v=VVxOPiDVwNQ

**Comment by Schmoozerd** [comment]
hmm, there is an areatrigger near the npc, but this looks rather like being handled by getting near enough the npc - likely eventAI will be proper way to toggle faction/ cast this mind-probe spell.

**Comment by cala** [comment]
> likely eventAI will be proper way to toggle faction/ cast this mind-probe spell.

In fact, I already wrote about 95% of the full script with EventAI. I was planning to release it for v1.2.1 along with the full Blackrock Spire revamp, but I postponed it because EventAI was missing ACTION_T_SET_STAND_STATE at the time. Now it was added by Xfurry this WE in cmangos-classic, I should be able to finish the script (some phase changes were not right, IIRC).

**Comment by scotty0100** [comment]
Just noticed this was bugged again. Reason being I used https://github.com/scriptdev2/acid/commits/classic
over our creature_ai_scripts and this fix isn't including in their Acid. Does it need to be made into a PR to Acid or should  I not be sourcing Acid over the one included in classicDB?
