### ISSUE TITLE
AQ20 - Qiraji Gladiators Linking

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#426]
Link the Qiraji Gladiators guarding the guard ways in AQ20. I believe I have linked them in the correct way, SQL below for review. After a server reboot they were behaving as they should.

```
-- Link creatures Qiraji Gladiator spawns at the beginning of the dungeon. (87524 and 87523)
INSERT INTO `creature_linking` (`guid`, `master_guid`, `flag`) VALUES ('87524', '87523', '515');

-- Link creatures Qiraji Gladiator spawns just before entering Kurinnaxx (87521 and 87522)
INSERT INTO `creature_linking` (`guid`, `master_guid`, `flag`) VALUES ('87521', '87522', '515');

-- Link creatures Qiraji Gladiator spawns after General Rajaxx (87518 and 87517)
INSERT INTO `creature_linking` (`guid`, `master_guid`, `flag`) VALUES ('87518', '87517', '515');

-- Link creatures Qiraji Gladiator spawns after General Rajaxx (87520 and 87519)
INSERT INTO `creature_linking` (`guid`, `master_guid`, `flag`) VALUES ('87520', '87519', '515')
```

**Comment by scotty0100** [comment]
Source: 
http://www.dailymotion.com/video/x8s641_wow-raid-aq20-rashgarrot_videogames&start=66

**Comment by Tobschinski** [comment]
Hi,
I've been able to pull a single one on retail. So I'd assume they are only linked to a boss and not to themselves (the first two packs to Kurinaxx, the third to Buru and the last one to Moam, to not let them spawn while bosses are dead)

Your mentioned issue occurs in many raid-dungeons and is pretty much caused by an insufficient setting in the mangos.conf at CreatureFamilyAssistanceRadius. It needs to be stored in creature_template for each creature to solve this issue in general. 

I am 100% sure, 10 yards range (default) is not correct for Qiraji Gladiators.

**Comment by cala** [comment]
> I've been able to pull a single one on retail

I'm pretty sure it was impossible to pull a single one while on level 60/70 and even was not intended. Maybe it is now possible (which means that calling assistance should take player level as an argument...)

Just wondering.

**Comment by Tobschinski** [comment]
No no, if you pull any of them, both will join the fight. The radius isn't changed.

But in order to check if they are linked to aggro on aggro you need to have a third creature, that patrols in the area. You need to pull it exactly when its CallForHelp-radius overlaps one, but not the other Gladiator. 

If only one will add, they are not linked. (at least to aggro on aggro)

**Anyway, this is just the retail behavior. Until, we do not have different values for each creature, linking is probably the best solution.**

EDIT: With that method, I've been able to pull a single Scorpion in AQ40 as well. (the ones after Fankriss)

**Comment by cala** [comment]
Thank you for clarifying, I misunderstood what you were meaning. So, yes, I agree that linking is probably the best option here.

**Comment by cala** [comment]
Just a note to @scotty0100 : 
flag 515 is 512 + 1 + 2 which are : FOLLOW_MASTER + AGGRO_ON_AGGRO + AGGRO_ON_SLAVE_AGGRO.
So, the flag 512 is irrelevant here as the NPCs are statics.
You might want to use the flag 4 + 8 that make each NPC (master/slave) respawn when the other evades, but I'm not sure those NPCs had this behaviour.

**Comment by Tobschinski** [comment]
Nope!

![respawnglad](https://cloud.githubusercontent.com/assets/4753528/3029946/f3ccc984-e03a-11e3-963e-e2999c08eb8d.png)

They will just never respawn if earlier mentioned bosses are dead and if they do they will respawn as a pack and not independent.
