### ISSUE TITLE
Quest "Electropellers" (Darkshore) - unable to get quest items from Fishing

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#441]
This quest is time-consuming by itself and also it is very time consuming to understand that is does not work at all -  in any of supposed areas.

INSERT IGNORE fishing_loot_template (entry, item, ChanceOrQuestChance) VALUES
  ( 456, 6718, -20), -- Cliffspring River (ID in AreaTable.dbc)
  ( 454, 6718, -20), -- Wildbend River
  ( 448, 6718, -20); -- Grove of the Ancients
");

YTDB/UDB/PSDB contain area IDs, but they seem to be partially wrong.

**Comment by cala** [comment]
Thanks for this report and for providing the fix!

**Comment by evil-at-wow** [comment]
It seems like you're missing at least one entry (Cliffspring Falls). The notes in my list have this at the moment:

-- Fix missing fishing loot for quest 1580, "Electropellers".
DELETE FROM `fishing_loot_template` WHERE item = 6718;
INSERT INTO `fishing_loot_template` (entry, item, ChanceOrQuestChance, groupid, mincountOrRef, maxcount, condition_id) VALUES
(445, 6718, -20, 0, 1, 1, 0), -- Cliffspring Falls
(448, 6718, -20, 0, 1, 1, 0), -- Grove of the Ancients
(454, 6718, -20, 0, 1, 1, 0), -- Wildbend River
(456, 6718, -20, 0, 1, 1, 0); -- Cliffspring River

El's Extreme Anglin' site stated the following in TBC times:

> The second quest requires 12 Electropeller, which can be caught from any inland open water.

So what about Ruins of Mathystra? Twilight Vale?

**Comment by Neotmiren** [comment]
Quest text states "river or lake" and then "some lake or stream in Darkshore". "Any open inland water" seems not correct because no one on wowhead mentions "The Master's Glave" (is that what you refer as Twilight Vale? it is not true lake). And the creek of Cliffspring River is not "inland water".

Ruins of Mathystra (water in the alpha Blackfathom Deeps entrance?) also is not mentioned and is not a lake.

Yes, "Cliffspring Falls" should be added because it is mentioned in wowhead comments and it is "stream" (but not "river", that is why I excluded it - it seemed more logical).

**Comment by evil-at-wow** [comment]
I don't remember why exactly I added that question to my notes. Probably because there's water and I wanted to check any references for these areas too. I agree the water in The Master's Glaive is probably to shallow to fish in anyway.

That said: quests texts are not always 100% accurate, as we all know, and El's Extreme Anglin' has proven to be a very reliable sites when it comes to fishing. So I would not automatically rule out every piece of water that is not exactly a river or lake because the quest text says so. But realistically speaking, we probably won't be able to prove anything - positive or negative - for these two areas any more. So I'm fine with dropping them.
