### ISSUE TITLE
Stratholme - Missing Weapons

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#445]
A few NPCs in Stratholme are missing their weapons in and outfight, including ...

I have no idea which IDs are needed.

Grand Crusader Dathrohan 
![](http://wow.zamimg.com/uploads/screenshots/normal/39125.jpg)

Archivist Galford
![](http://img2.wikia.nocookie.net/__cb20080116105041/wowwiki/images/7/7a/Archivist_Galford.jpg)

Malor the Zealous
![](http://img2.wikia.nocookie.net/__cb20080229224100/wowwiki/images/thumb/b/b0/Malor.jpg/200px-Malor.jpg)

Cannon Master Willey
![](http://img2.wikia.nocookie.net/__cb20070912100045/wowwiki/images/thumb/5/5c/Willey.jpg/200px-Willey.jpg)

**Comment by evil-at-wow** [comment]
Coincidently, I parsed some Stratholme data recently (version 3.0.3 build 9183) :grin: 

So I checked the IDs for the NPCs above, and this is what I got:

| Name | Main hand | Off-hand | Ranged |
| --- | --- | --- | --- |
| Grand Crusader Dathrohan | 12949 | NA | NA |
| Archivist Galford | 12742 | NA | NA |
| Malor the Zealous | 12950 | NA | NA |
| Cannon Master Willey | 11763 | 11763 | 12523 |

Because I vaguely remember seeing at least two of the above NPCs without weapons on my TBC server too, I checked them again ingame. And indeed: TBC-DB has the same issue! So I figured I could as well write a quick fix while I was there:

```
DELETE FROM `creature_equip_template` WHERE entry IN (10812, 10811, 11032, 10997);
INSERT INTO `creature_equip_template` (entry, equipentry1, equipentry2, equipentry3) VALUES
(10812, 12949, 0, 0), -- Grand Crusader Dathrohan
(10811, 12742, 0, 0), -- Archivist Galford
(11032, 12950, 0, 0), -- Malor the Zealous
(10997, 11763, 11763, 12523); -- Cannon Master Willey

UPDATE `creature_template` SET equipment_id = entry WHERE entry IN (10812, 10811, 11032, 10997);
```

Note that the entries in creature_equip_template are a free choice according to the documentation, so I just went with the NPC entries here (instead of whatever random assignment that seems to be currently used). I verified the new entries were still unused in TBC-DB, but please check your DB too (or adjust the entries as you see fit).

But! There seems to be more, because my core now complained that the items for the first three NPCs are unknown. So this only fixes Cannon Master Willey for me, and I bet it is not a coincidence that only the items for Cannon Master Willey are present in my item_template table (even though the documentation for creature_equip_template mentions that the items have values from Item.dbc). I'm not sure what's going on here yet. To be continued...

**Comment by cala** [comment]
The items listed above are only used as NPC equipment (and as such, their name usually starts by "Monster" followed by the type of weapon "axe", "sword" and its color, like [this one: item 12949](http://www.wowhead.com/item=12949) ). This means that these items are never accessible to players and thus they never were added in `item_template`.

In TBC, WotLK and Cata core, knowing the entry of such item is enough as the core knows how to display it from DBC files. This is not the case in Classic core (see issue #290 ) were NPC equipment is taken from `creature_equip_template_raw`. This table is using the displayId of the item instead of its entry. So, to fix this issue, I had to retrieve those display IDs either from other DBs (easy way) or screenshots compared to other items (hard way) and add the missing entries.

The NPCs in the two Ahn'Qiraj dungeons who are missing their weapons will be fixed the "hard way". :(

**Comment by ghost** [comment]
Why can't you store the _monster_ items in the `item_template` table? 

Also considering all the _monster_ items seems to be stored on wowhead(if you know the ID to the item) it should be fairly easy to find the Display ID in the website "source code" for the 3D viewer, for example with the _monster_ item you linked to: `"displayid":23508`

**Comment by cala** [comment]
Adding the items to `item_template` won't change anything as the core does not use that table for NPCs equipment. Moreover, beside their entry (and displayid) we don't have enough data about those items to properly fill all the `item_template` fields. This is probably for the same reasons those items are also missing in all other DBs.

As for the display ID, thank you for the suggestion. We can also find them from DBC files and in fact, extracting them from DBC files is more reliable than wowhead. This website has many usefull data, but as time goes by it is less and less a reliable source for Classic content and we have to find workarounds.

**Comment by ghost** [comment]
I agree with you that a lot of the content on wowhead is deprecated by now, I think the _monster_ items can be an exception if you only need a visual identifier to how it looks in the screenshots, but I fully with the DBC files being a superior method.

But you mentioned that there's not enough information about the _monster_ items to fill the `item_template` table, but isn't `entry`, `class`, `subclass`, `displayid` and `InventroyType` all that is required? Wowhead has parsed all this information and if it's **only** used as a visual identifier wouldn't that be adequate as long as it got the correct visual and is equipped in the way it is supposed to be? 

_(I hope I don't come off as trying to interrogate you, I am just trying to learn this and get a better understanding so please correct me if I am wrong here.)_

**Comment by evil-at-wow** [comment]
I didn't know about the Classic vs other cores difference for NPC equipment, so good to know. And indeed, you can find display ID info in the DBCs files, so it's not that hard to find correct values for Classic then.

> In TBC, WotLK and Cata core, knowing the entry of such item is enough as the core knows how to display it from DBC files.

Well, apparently not, because I got the correct entries and it didn't fix the NPC equipment on my TBC server (except for one case, where item_template is filled). But no worries, I'll figure out what I missed later.

> The NPCs in the two Ahn'Qiraj dungeons who are missing their weapons will be fixed the "hard way".

I haven't actually checked yet, but I did quite a few AQ20/40 runs back in the days so no doubt there's some useful data in my data archive. I'll check and parse them and let you know the correct IDs (I assume you are talking about #425). Translating them to display IDs will be left as an exercise :wink:
