### ISSUE TITLE
[Object] Onyxia's Gate

### ISSUE THREAD

**Issue by Swater96** [classicdb/database#45]
GUID:9091

Should be locked and require the Drakefire Amulet (http://www.wowwiki.com/Drakefire_Amulet) attained by completing the Onyxia's Lair Attunement quest chain (http://www.wowwiki.com/Onyxia%27s_Lair_attunement) 

Code can be used from the Dragonspire Door GUID:82597 which requires the Seal of Ascension (http://www.wowwiki.com/Seal_of_ascension) to open

**Comment by cala** [comment]
Thank you for the report. What do you mean by "Should be locked"? The maws should be closed and are not?

**Comment by Swater96** [comment]
Onyxias lair required attunement and right now it's possible to open the gate leading to the portal without the Drakefire Amulet in your bags.

**Comment by cala** [comment]
I'm not sure the Drakefire Amulet was required to open the gate. You need the attunement to enter the raid portal, for opening the gate, I don't know.

**Comment by Swater96** [comment]
Actually I think you're correct, I seem to remember the portal keeping me out in retail. Do you think adding an item req. for the portal can be done in the db? I scripted it many years ago on a server, but I can't find it in my archives.

**Comment by cala** [comment]
I just looked into the DBC and the Drakefire Amulet (item 16309) is never used as a key.
So unfortunately, you cannot lock the Onyxia's Gate via the database, at least not in the proper way via `gameobject_template`. In order to lock that gate and open it only with item 16309, you probably need to write a script in SD2.
