### ISSUE TITLE
Rares that don't drop anything

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#568]
Rare's should always at least drop 1 green.

Issue was mentioned before here: https://github.com/classicdb/database/issues/49 but was decided we should do it on a per mob basis as its' easier to track down/fix.

<b>Burning Steppes</b>
<b>Name - Dropped</b>
Gorgon'och - Only silver
Gruklash - Only silver
Deathmaw - Tender Wolf Meat

Are 3 I've come across today - a player of mine has uploaded a document onto Google Drive with their experiences with rare mobs and drops which also could be useful - if it's blank it means they haven't found/killed them yet. But there are a lot of rares that are marked with only dropping money, or in some cases a blank loot table.

https://docs.google.com/file/d/0B31upn5Ac96za1ZmSXNBdUJxaHc/edit?pli=1

@cala Did you want me to break down the Google Document per zone and create separate issues per zone to make it easier to manage?

**Comment by cala** [comment]
Thanks for this report and list. I still did not make my mind about how to manage this.

**Comment by Metalica** [comment]
Information:

I went thru rares and found out that all "blue" items have 0% chance drop. So making one by one is the key.

**Comment by Schmoozerd** [comment]
are you sure such items are not wrapped together in a group?

**Comment by Metalica** [comment]
@Schmoozerd 

 Correct they are in group. 

 Test made before i 1st. posted here:

 Npc name: Bannok Grimaxe.

 Before update: INSERT INTO `db`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES ('9596', '12621', '0', '1', '1', '1', '0');

 Default DB with 0% drop, group 1. = no drops.

 Updated update: INSERT INTO `db`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES ('9596', '12621', '33', '1', '1', '1', '0');

DB updated with correct % (to my logic) drops = 1 drop per instance.

 My conclusion: Items actualy drop, then before not at all.

**Comment by Schmoozerd** [comment]
You need to read the documentation.

Having chance = 0 and group = 1 (mincountOrRef > 0) is proper, and likely in this case also correct.

**Comment by Tobschinski** [comment]
> A group may consists of explicitly-chanced (having non-zero ChanceOrQuestChance) and equal-chanced (ChanceOrQuestChance = 0) entries. Every equal-chanced entry of a group is considered having such a chance that:
> 
> all equal-chanced entries have the same chance
> group chance (sum of chances of all entries) is 100%

https://github.com/cmangos/issues/wiki/loot_template

**Comment by Phatcat** [comment]
https://docs.google.com/spreadsheets/d/1Bli1uzBZD8hyphXF_QqaFpLmpLNAZKd5ItDp9U_yOrs/edit#gid=0 

My list includes cached allakhazam links for all uninstanced vanilla rare mobs (yes, I'll get around to adding the instance rares eventually) - Just if someone feels bored and wants to check which rares have specific loot, if our current rates are somewhat off, or which ones only have world loot.

**Comment by Zooke** [comment]
There are plenty of old world rares that drop unique items. I used to always kill that mob in NE Redridge for a chance at that rare BoE sword. That's part of the database I have not got to grips with yet, the way loot is grouped and extra items added to the table, and their rates.
Now that you have brought life to the subject of rares, there is 1 huge element missing from them. A random spawn timer, something like (min time) + (random time defined by min/max).
i.e. allowing a respawn from from anywhere between 10 and 30 minutes, or even between 36 and 84 hours depending on the rare. Of course all of this would involve a fair amount of guesswork since no-one has the exact numbers.
http://www.amazon.com/World-Warcraft-Atlas-Second-Brady/dp/0744010470/ is probably the best reference for the spawn windows I think.

**Comment by Zooke** [comment]
For instance Foe Reaper 4000 had these 2 unique drops.
http://db.vanillagaming.org/?item=933 Large Rucksack
http://db.vanillagaming.org/?item=4434 Scarecrow Trousers
Vultros dropped the rare quality claw dagger etc.
I still have my old _npcscan file where I added every old world rare, so I suppose I was a bit anal about them :(

**Comment by Zooke** [comment]
@Phatcat I'll work through that list

**Comment by Phatcat** [comment]
@Zooke you don't have to but you're very welcome to. If you give me about 20 min I can have all the instance rares added as well.

**Comment by Zooke** [comment]
no need, I will add them as I go.
My old custom _npcscan file should have all the games rares.
[_NPCScan.zip](https://github.com/classicdb/database/files/309261/_NPCScan.zip)

https://github.com/classicdb/database/commit/6dc28c364c01b078ddb323582c9ab1138463cc3f
is something I think needs more thought, 0.03%, not far off the chance of running ICC and Ulduar and getting both mounts in the same day. Wowhead data may be the best we have, but these sort of numbers just scream that something is not right somewhere. 3976 recorded loots from a mob that's been in the game for 10 years ? The data post Cata especially I think can be very misleading.

**Comment by Zooke** [comment]
@Phatcat I haven't forgotten about this, just finishing my way through that bugged quests list.

**Comment by Phatcat** [comment]
Yeah, I had taken on this but sadly havn't had the time to follow up on it much since I created the list...
It may also not contain 100% all rares but it should be pretty damn close.

Edit: @Zooke for vanilla I would rather go by Allakhazam if you're gonna get data from a db site, since wowhead got set up sometime in late 2005 or early 2006 if I don't remember incorrectly, so at least for vanilla allakhazam does have a bunch more data. Cross referencing the 2 may be even better, though.

**Comment by killerwife** [comment]
@Zooke I will release our rare mob loot pools when they are done. It should be in next 1-2 weeks. Then you can integrate it into classic-db as you wish.

**Comment by cala** [comment]
@Killerwife That would be great ! Thank you. :+1:

**Comment by cala** [comment]
Issue followed up in https://github.com/cmangos/classic-db/issues/2 so I'm closing this one.
