### ISSUE TITLE
Sarilus Foulborne NPC #3986

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#597]
This npc is the focus for the Mage Summoner quest in Ashenvale.  When engaged all foulborne does is autoattack melee and is supposed to have two main abilities.  Frostbolt (spell 20806) and Sarilus's Elementals (spell 6490).  This npc is currently not flagged for EventAI in the DB.

**Comment by Tobschinski** [comment]
Not sure if I should not fix this right away.

Since the core will use calculated stats instead of the ones stored in creature_template, the whole encounter would be incredible harder to survive. (He will summon 2-4 Guardians every 25 seconds and they would be level 25 instead of level 1)

**Comment by cala** [comment]
The various isses regarding the NPCs stats/level are pending a core update I will write in a few days/weeks.

So, the work on fixing this NPC can be started and push to ACID as a pull request when core is fixed.

**Comment by Tobschinski** [comment]
Done already, don't bother with it.

**Comment by cala** [comment]
Nice, thank you!

**Comment by cala** [comment]
Quick update on this: I'm currently testing a core patch that should fix the level of summoned NPCs.

**Comment by Phatcat** [comment]
According to this comment here;
https://web.archive.org/web/20181028091220/https://www.wowhead.com/npc=3986/sarilus-foulborne#comments:id=396446
His elementals should be level 25, but it also states that it used to be easier, so is this only correct for wotlk? are guardians summoned by mobs on classic and tbc not setting the correct level?

**Comment by Phatcat** [comment]
His summons do have a very strange behaviour though because according to these comments;
https://web.archive.org/web/20181028091220/https://www.wowhead.com/npc=3986/sarilus-foulborne#comments:id=702108
https://web.archive.org/web/20181028091220/https://www.wowhead.com/npc=3986/sarilus-foulborne#comments:id=899064
they should be hostile towards the other acolytes on the hill and start killing them once he is done with the player.

**Comment by Phatcat** [comment]
what the... I didn't unassign anyone.

**Comment by cala** [comment]
We have conflicting comments in the links you gave @Phatcat. Some say the elementals are level 1, some other that they are level 25 (same level as their summoner because they are set to level 1 in the database). Currently, the elemental's level is automatically set by the core.

So, either the level was changed across time (starting to WotLK from what the comments hint) or they always were level 25 but should have such a low HealthMultiplier that than can easily be killed by Thunderclap (
https://web.archive.org/web/20181028091220/https://www.wowhead.com/npc=3986/sarilus-foulborne#comments:id=141613).

I wonder if we can find out more.

**Comment by Tobschinski** [comment]
Quite possible that they have been level 1 at some point of the game, spell 6488 - Sarilus's Elementals Passive hints this. (gives them hit and damage aura)

Idk how though, they're guardians.

**Comment by cala** [comment]
Now working as it should. Closing this issue.
