### ISSUE TITLE
Items of Power Mage Quest

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#600]
This quest does seem to function but on occasion decides to not work.

I can't put my finger as to why as everything in the DB seems to match up, perhaps another set of eyes would be able to see as to why.

Best way to test is to add the quest, get the Jade, and summon about 100 Witherbark Sticks and try summoning the Bolt 10 times around the Stone of Outer Binding.

Seems to work about 75% of the time - I think it may be getting interrupted and then just eats the sticks and does nothing. So might be harder to replicate on a LAN server with not a lot of latency.

Also the Bolt Charged Bramble should be hovering above the stone, and not at the casters' feet

Source: http://www.wowhead.com/item=7272#screenshots:id=21924

**Comment by cala** [comment]
Thank you for reporting.
Along with the Bolt Charged Bramble not hovering above the stone, it should also be struck by a lightning bolt (Spell 10387). Unfortunately, to fix these, the core needs to be updated to allow GO to cast spells (currently, only units can cast spells).
As for the spell not working 100% of the time, yet consuming the sticks, this is probably due to the trap GO spawned _after_ the spell using the sticks is casted. If player is GM (mode on) or if player is too high level or trap failed/resisted, then the charged bramble is not spawned but the sticks are stil consumed. There were however a few reports of the quest not working 100% of the time on retail, players complaining they have to gather the sticks again.

I spent a lot of time on this quest previously and the result is in
https://github.com/classicdb/database/commit/376504dcd097cc37cf09065048bc155b09885a16
The original issue can still be seen there: https://github.com/classicdb/database/issues/7
In the current state of the core, this is the best I can do DB-side without breaking again the quest.
