### ISSUE TITLE
NPC #5595 Guid #1894 Missing Waypoints

### ISSUE THREAD

**Issue by Zingzah** [classicdb/database#602]
This ironforge guard missed out on his patrol route when his other colleagues received theirs in the last update.  I added some waypoints for this npc that mirrored his counterpart patrolling the opposite side of the Forge as close as I could if this is helpful.

INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 1, -4761.37, -1157.62, 502.213, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.698499, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 2, -4796.16, -1114.85, 498.806, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.28893, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 3, -4804.42, -1111.48, 498.806, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.21825, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 4, -4815.41, -1081.27, 502.213, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.35744, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 5, -4808.1, -1030.53, 502.208, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6.20647, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 6, -4769.45, -1035.99, 502.211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5.33076, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 7, -4734.71, -1078.26, 502.211, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5.40537, 0, 0);
INSERT INTO `creature_movement` (`id`, `point`, `position_x`, `position_y`, `position_z`, `waittime`, `script_id`, `textid1`, `textid2`, `textid3`, `textid4`, `textid5`, `emote`, `spell`, `wpguid`, `orientation`, `model1`, `model2`) VALUES (1894, 8, -4737.32, -1137.14, 502.209, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3.74189, 0, 0);

**Comment by cala** [comment]
This one was also on my to do list since https://github.com/classicdb/database/issues/508, thanks for taking care of it.
I tested your fix and I agree with the pathway. Could you please make a pull request so we could merge it?
In case you need it: [How to make a pull request](https://help.github.com/articles/using-pull-requests)

I also have a few enhancements that can be brought to your fix:
- an `UPDATE` query should be done to set `MovementType = 2` for this NPC entry in `creature` table
- the pathway along the Forge is a bit too polygonal in my opinion. I suggest that you add two waypoints to make the pathway follow more closely the circular wall of the Great Forge

If you don't feel/know how to add these changes to your current fix, just do a pull request, I'll add them after.
