### ISSUE TITLE
Thaurissan Relic

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#649]
When you're alone and click on the gameobject, it counts normally. But if you're in a group and both players activate the gameobjekt directly one after another it counts double for BOTH players.
There should also appear one of the following texts when activating them.

Gameobject: http://www.wowhead.com/object=153556
Quest: http://www.wowhead.com/quest=3701

Texts:
"A tormented voice whispers: You will perish here. <Your mind fills with visions of chaos and destruction.>"
"A tormented voice whispers: Leave this place. <The relic emits a white hot arc of flame. A memory has been gained: A lone Dark Iron dwarf is surrounded by seven corpses, kneeling before a monolith of flame.>
"A tormented voice whispers: Defiler... you will be punished for this incursion. <A symbol of flame radiates from the relic before it crumbles to the earth.>"
"A tormented voice whispers: Help us, outsider. <The relic crumbles to dust. A vision of eight Dark Iron dwarves performing some sort of ritual fills your head.>"
"A tormented voice whispers: Your existence is acknowledged. <The relic turns to dust. Your head throbs with newfound wisdom. Something evil lurks in the heart of the mountain.>"
"A tormented voice whispers: He cannot be defeated. <The relic burns to nothing. The memories it held are now your own. This city was destroyed by a being not of this world.>"
"A tormented voice whispers: Do not taint these ruins, mortal. <You are engulfed in a blinding flash of light. A creature composed entirely of flame is the only thing you can remember seeing.>"

Content Version: Classic DB version 1.4.1 'Toward the Fiery Heart'. For CMaNGOS z2525 and Scriptdev2 z2703 (update 0786_quest_template applied to mangos db)
Creature AI: ACID 1.12.x (Classic) for CMaNGOS-CLASSIC (1.12.X Client)

**Comment by cala** [comment]
From what I read in the wowhead quest comments, the texts you listed were added in 2.0 (pre-TBC release patch), so they might not be for Classic.

Regarding the reward issue, I will see if this is a core or DB issue.

**Comment by Metalica** [comment]
It is classic text info: http://www.wowhead.com/quest=3701/the-smoldering-ruins-of-thaurissan 

 Note: See when added: Added in patch 1.11.1

**Comment by cala** [comment]
I would need @xfurry or @Schmoozerd help on this matter.

Basically, the issue is:
For a quest, player has to use 12 spawns of GO 153556 which is of type `GAMEOBJECT_TYPE_GOOBER`
Using the GO does grant 1/12 quest credit but should also make NPC 8887 whisper to player one random text from 8 texts.
This could be easily done with : 

``` SQL
INSERT INTO `dbscripts_on_go_template_use` (`id`, `delay`, `command`, `datalong`, `datalong2`, `buddy_entry`, `search_radius`, `data_flags`, `dataint`, `dataint2`, `dataint3`, `dataint4`, `x`, `y`, `z`, `o`, `comments`) VALUES
(153556, 1, 0, 4, 0, 8887, @NPC_GUID, 19, @TEXT1, @TEXT2, @TEXT3, @TEXT4, 0, 0, 0, 0, 'Thaurissan relic - random whisper');
```

This works nicely, but this limits the number of texts to 4 instead of 8.

I tried then to use `dbscripts_on_go_use` instead for each of the 25 spawned GOs, with the same line of script, but I randomized the 8 texts amongst those 25 GOs.

This does not work. The script is not even handled (not a single mention of it in the log file, while it is perfectly displayed with `dbscripts_on_go_template_use`), no error in DBLog either. I'm puzzled and saw nothing in core code (at least with my limited knowledge) that would explain while this script is not handled in `dbscripts_on_go_use` but is in `dbscripts_on_go_template_use`.

Do you have any idea where I should look at, please? Thanks.

Note: if you want to test the script you must first force load/activate the NPC id 8887 since Blizz spawned it far away from where the GOs are (official data on its spawn position).

**Comment by evil-at-wow** [comment]
Using dbscripts_on_go_use doesn't work here because the scripts aren't run for this type of GOs. If you have a look at the function GameObject::Use (in GameObject.cpp), you can see that the templates ones are always run (assuming scriptReturnValue is false): `GetMap()->ScriptsStart(sGameObjectTemplateScripts, ...)`.
But the non templates ones are only run for `GAMEOBJECT_TYPE_DOOR` and `GAMEOBJECT_TYPE_BUTTON`.

I couldn't tell you the why however, because I don't know if this is intentional or not, or something that was never implemented for other types because there was no need, etc.

**Comment by cala** [comment]
Thanks @evil-at-wow, I understand it better (and the [wiki confirms it](https://github.com/cmangos/issues/wiki/DBscripts#the-dbscripts_on_-tables)). What is strange is that there are no check for this in ScriptMgr.cpp when this table is loaded.
Whatever, I see no reason for `GAMEOBJECT_TYPE_GOOBER` for not being used with `dbscripts_on_go_use` and I think we should allow the core to handle goober for scripts. This quest is an example that we need something for that.

**Comment by cala** [comment]
Below is my patch proposal for core.

``` diff
 src/game/GameObject.cpp |    5 +++--
 1 files changed, 3 insertions(+), 2 deletions(-)

diff --git a/src/game/GameObject.cpp b/src/game/GameObject.cpp
 src/game/GameObject.cpp |    7 +++++--
 1 files changed, 5 insertions(+), 2 deletions(-)

diff --git a/src/game/GameObject.cpp b/src/game/GameObject.cpp
index 55d4a3a..4897806 100644
--- a/src/game/GameObject.cpp
+++ b/src/game/GameObject.cpp
@@ -1222,8 +1222,11 @@ void GameObject::Use(Unit* user)
                 player->RewardPlayerAndGroupAtCast(this);
             }

-            if (scriptReturnValue)
-                return;
+            // activate script
+            if (!scriptReturnValue)
+                GetMap()->ScriptsStart(sGameObjectScripts, GetGUIDLow(), spellCaster, this);
+            else
+               return;

             // cast this spell later if provided
             spellId = info->goober.spellId;
```

For more safety, it could be possible to add additional check before starting the script, but I see no real need here, though I'm open to suggestions.

While I was looking at this part of the code, I also noticed a duplicate block there:

``` c++
                else if (info->goober.gossipID)             // ...or gossip, if page does not exist
                {
                    if (!sScriptMgr.OnGossipHello(player, this))
                    {
                        player->PrepareGossipMenu(this, info->goober.gossipID);
                        player->SendPreparedGossip(this);
                    }
                }

                // possible quest objective for active quests
                if (info->goober.questId && sObjectMgr.GetQuestTemplate(info->goober.questId))
                {
                    // Quest require to be active for GO using
                    if (player->GetQuestStatus(info->goober.questId) != QUEST_STATUS_INCOMPLETE)
                        break;
                }

                if (info->goober.eventId)
                {
                    DEBUG_FILTER_LOG(LOG_FILTER_AI_AND_MOVEGENSS, "Goober ScriptStart id %u for %s (Used by %s).", info->goober.eventId, GetGuidStr().c_str(), player->GetGuidStr().c_str());
                    StartEvents_Event(GetMap(), info->goober.eventId, player, this);
                }

                // possible quest objective for active quests
                if (info->goober.questId && sObjectMgr.GetQuestTemplate(info->goober.questId))
                {
                    // Quest require to be active for GO using
                    if (player->GetQuestStatus(info->goober.questId) != QUEST_STATUS_INCOMPLETE)
                        break;
                }

                player->RewardPlayerAndGroupAtCast(this);
```

The block about the quest objective appears twice. Unless someone has a good explanation for this, I will also remove one of them.

**Comment by evil-at-wow** [comment]
That duplicate block of code looks like something that a typical merge mistake would cause. I've checked, and neither the WoTLK nor the TBC core has this - the first block isn't there - so I think you can safely delete it.

**Comment by cala** [comment]
Thanks, I will remove the duplicate block.

Since you are doing backports this WE, I'd like to push the patch above to allow DBScripts for goobers. Is this patch ok for you?

**Comment by evil-at-wow** [comment]
I'm not the expert, but I have no reason myself to reject that patch, so go ahead.

Coincidentally, I've had a similar problem some time ago where I need an NPC to say one of five different texts (or six, I forgot). And because it's a single NPC, your workaround/trick doesn't work there, so I believe we still need a real solution in the long run. We could just add extra columns, but perhaps we can come up with something better than adding four columns that no one uses, except for one or two special cases.

**Comment by cala** [comment]
I fully agree with you.
I still pushed the patch since, in my opinion, there is no reason that goober can't start scripts on GO use.
I also think that 4 different text entries is not enough though the cases when more are needed are very few. Thus, adding more columns to the table would be a waste of space. I can't help but notice that the X, Y, Z and O columns are not used with the SAY_TEXT command, so many we can modify the core to also use those columns as text entries if their value is different from zero? (I did not check if column type would allow this).

**Comment by evil-at-wow** [comment]
The coordinates are floats, so that would be tricky. It would also be very unexpected to use these fields for texts, so I'd rather not do that.

You know, If we'd really want, we could store 8 entries with the current database tables and only a few changes in the code. The four dataint columns are now used to store a text ID in a 32-bit integer type. But those text IDs aren't random 32-bit integers! No, they are matching an _entry_ in the db_script_string table, and they need to be in fairly small range starting at 2 billion. If you'd store the texts as offsets from the start of the range, you could 'pack' two such offsets in a single dataint column. A 16-bit offset gives you 65536 possible offsets, which is more than plenty to cover the "more than four strings needed" cases (or even all texts, for that matter).

We don't necessarily want to change the existing data, but we don't need to. Notice that the datalong and datalong2 columns aren't used either for SCRIPT_COMMAND_TALK, so we could use datalong2 as the 'base' for the text ID (datalong is a 24-bit type for some reason, so that doesn't work). If we do that, the datalong2 column could be used to make the distinction between "the dataint columns are text IDs" (datalong2 = 0) or "the dataint columns contain offsets, and these need to be added to datalong2 to get the actual text IDs" (datalong != 0).

This is easy enough to implement, though somewhat far stretched and certainly more complex to write (database devs), read or check/verify (everyone). But then again, the cases where you need more than four strings are very rare, so...

**Comment by Tobschinski** [comment]
There are only 5 out of 30.000+ spells that make use of every single reagents field, 8 in total. And still they exist. If you need more columns, just add them.

Awful workarounds by myself have been made to make things working, because the database's capabilities are rather limited. And I still don't think this was the proper way to do ...
