### ISSUE TITLE
Prequest of Libram of ....

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#668]
At the moment you don't need the prequest to start the following quests:
http://www.wowhead.com/quest=7483
http://www.wowhead.com/quest=7484
http://www.wowhead.com/quest=7485
Prequest: http://www.wowhead.com/quest=7482
Source: http://wowpedia.org/Quest:Libram_of_Focus

**Comment by cala** [comment]
Thank you for your report.

**Comment by cala** [comment]
Those three quests have two possible prerequists: 7482 and 7481 (Alliance and Horde version). Unfortunately, this case is not doable by core at the moment, so can't be fixed via DB either.
One possible workaround (but I would call that a hack) would be to use SD2 for that.
Closing the issue here as nothing can be done DB wise.
