### ISSUE TITLE
Wrong HP Highlord Omokk

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#678]
Highlord Omokk has only about 2,2k life.
http://www.wowhead.com/npc=9196

**Comment by Metalica** [comment]
http://db.valkyrie-wow.org/?npc=9196

UPDATE `creature_template` SET `MinLevelHealth`='23200', `MaxLevelHealth`='23962' WHERE (`Entry`='9196')

UPDATE `creature_template` SET `MinMeleeDmg`='1190', `MaxMeleeDmg`='1416' WHERE (`Entry`='9196')

**Comment by Tobschinski** [comment]
A named NPC that has a range of level? Sounds odd, at least to me. I'd like to see their source.

But you got a point with Omokk being broken.

**Comment by cala** [comment]
Their source is pretty simple : it very looks like an old fork of the old database, Classic DB is built upon, with the exact same mistakes like this one. This is why I don't use private servers data as sources: most of them are built from mangos core/database from years ago and still carry on bugs that are fixed (at least partially) and people think they are blizzlike because those private servers say so.

In this perticular case, the bug in Classic DB comes from a typo when updating the NPC's stats.
Its max HP should be 22272 but the last 2 is currently missing and its min/max level should be 59.

**Comment by Metalica** [comment]
There are two things that are more difficult than making an after-dinner speech: climbing a wall which is leaning toward you and kissing a girl who is leaning away from you.

 Your ego can become an obstacle to your work. If you start believing in your greatness, it is the death of your creativity.

 Wanted to help out with this db, but ludicrus egoistical people turn me away.....

**Comment by cala** [comment]
Despite what you are implying, what I wrote above is not egocentered answer, this is plain fact. Try to get the HP values of Highlord Omorokk from Classic DB back in [1.4](https://github.com/classicdb/database/archive/v1.4.0.zip) and you will get the exact same values than valkyrie wow. Why? Because guys from valkyrie wow took months/years ago the mangos DB and used it as their own. And they did not fix Omorokk since.

We tried to fix it recently (EDIT: fix occured in rev 0745 at line 8975 and the typo there is pretty clear), we made a mistake that was found and we are on the verge on fixing it. You may be upset if you want, but this is no secret that we try to do things properly and that private servers _are not_ reliable sources by design. We are not turning your help away, we are challenging it. Everyone's contribution can be and is challenged when we are not 100% sure of it, even mine.

And I dare say that calling people overproud when they point out that you give (partly) wrong information is a bit ironic.

**Comment by ghost** [comment]
@Metalica I think you misunderstood what Cala meant, he didn't mean to come off as ludicrous or egoistical, he just meant that the level range/stats from the source you linked is wrong, which can be confirmed by checking it with older versions of wowwiki or the Bestiary book. It's meant to be 59 [http://www.wowwiki.com/Highlord_Omokk?oldid=353604] but on Valkyrie's DB it's 58-59.

**Comment by Swater96** [comment]
private server online databases are not a source. Even putting up a website with the latest version of classicdb would be seriously flawed and filled with inaccuracies.
