### ISSUE TITLE
Guard Roberts

### ISSUE THREAD

**Issue by Metalica** [classicdb/database#696]
- Female model instead of male.

http://www.wowhead.com/npc=12423/guard-roberts

**Comment by Tobschinski** [comment]
Please check if you have applied https://github.com/classicdb/database/commit/57f60b4010c09e3dd6ce674bcea7d9fbb27f229a .

**Comment by Metalica** [comment]
You fix worked tnx, 1 more to go. Updated bug report.

**Comment by Tobschinski** [comment]
Hm, I don't think this is a DB-issue, both, Guard Roberts and his template use model_id: 3258, which is male. 

I don't know when things are going bad, to be honest.

**Comment by Metalica** [comment]
Np, we will figure it out.

**Comment by Tobschinski** [comment]
What model does he have if you delete your WDB folder?

**Comment by Metalica** [comment]
Deleted WDB due to my own work like 5 times, same female model.

**Comment by Tobschinski** [comment]
Okay, thanks to Schmoozerd's latest post in https://github.com/classicdb/database/commit/7fa789d42da8d39dcec06596474d159551dd584d - I was able to identify the problem in `creature_model_info`.

modelid, bounding_radius, combat_reach, gender, **modelid_other_gender**, modelid_other_team
'3258', '0.306', '1.5', '0', **'3257'**, '0'

But who is going to have a father-son-conversation with Guard Roberts to make him finally clear that he's a boy?

To be honest, I don't know if it's proper to just remove the marked modelid. 
The Stormwind Guards, who also make use of model 3257 and 3258 have alternatives stored in creature_template. They would still  look different.

**Comment by Metalica** [comment]
Up to you, but due to the model ID, i have deleted. Since it must be male. 

 Edit: working, up to you if you wanna close or not.

**Comment by cala** [comment]
Setting `modelid_other_gender` to zero for entry 3258 will work. But I'm not sure this is the proper thing to do.

All the other databases have the same values for this entry. So : 
- if all the values come from sniff and we must not change them
- if we are free to update the values of this table, we must do it very carefully because other NPCs use that entry

That is why I don't know how to fix this properly via DB, right now.

**Comment by Metalica** [comment]
I think i will need to end my discussion here, with simple statment.

 If your sniff data is not 1.12.1. And/or you use any sniff data from 2.4.3 or 3.3.5 is all wrong. Your argument regarding "sniff" data is also all wrong. Becouse your showing us wrong info. What is not in online databases all ower the internet.

 If it is from 1.12.1, then i apologise.

 To other developers:

 Delete the model id and and add female/male problem for guards creature template (model1,2). Problem solved.

**Comment by Tobschinski** [comment]
But you need to understand that we need and want to know who filled the table at some time in the past and even more important, why. Both of us weren't present at that time.

You can, of course, go along change everything you want on your side.

**Comment by Schmoozerd** [comment]
model_info_template was created by NF a long time ago with some sniff and dbc data.
Unfortunately he did not properly document why it was filled this way ;(

**Comment by cala** [comment]
Thank you Schmoozerd for clarifying this. Unfortunately, we still don't know if we are free to modify that table to fit our need here.

I see three possibilities:

1- remove `modelid_other_gender` while taking care of not breaking other creatures using that same  entry
2- modify core to enforce the use of the `modelid` value and not one of the alternate version when  this value is different from zero in `creature` table
3- do nothing as this is not a "big" issue

From my point of view, the third option is lazyness. The second one implies to agree on this matter with all DB projects and probably change many entries in the `creature` table (and even introduce a few issues to only solve one). That leads to using the first one.

**Comment by Tobschinski** [comment]
Okay, now I know for sure: There is bad data in `creature_model_info`. Have a look at [Mountaineer Zaren](http://www.wowhead.com/npc=1281) in Loch Modan - model 1812 & 4887. 

![](http://wow.zamimg.com/uploads/screenshots/resized/403105.jpg)
![](http://wow.zamimg.com/uploads/screenshots/resized/445564.jpg)

**Comment by cala** [comment]
I don't see the problem here. There are both female dwarf models. :D

**Comment by cala** [comment]
On a more serious note, here is my proposal in order to fix the current issue. I'd like to have your opinion on the matter.

How it is now:
- modelid 3258 is used by only two NPCs: Guard Roberts (12423) and Stormwind Guard (1423)
- Stormwind Guard has also modelid2 = 3257
- modelid 3258 is male, modelid 3257 is female
- currently, they both are cycling one another as alternate gender model

What I suggest:
- based on Metalica feedback, we know that removing `modelid_other_gender` for model entry 3258 solves the Guard Roberts' model issue
- this will however change the ratio of male/female Stormind City Guards because when the core will spawn a guard, it will spawn 50% of modelid1 which is modelid 3258 (male) and 50% of modelid2 which is modelid 3257 for 50% and modelid 3258 for 50% since there is an alternate gender set. With this, we end with 75% of male Stormwind City Guards and only 25% female. With such a ratio, I'm afraid that the male Stormwind City Guards would have to fight one another in order to conquer the love of the few female Stormwind City Guards. We don't want that to happen. So, I suggest to also remove the `modelid_other_gender` for modelid 3257
- Yet, doing so will bring another issue as creature 1642 (Northshire Guard) is also using modelid 3257 as modelid2. I think that this is an error and that using modelid1 = 3167 is enough because looking at others DB show that all creatures using modelid 3167 have either 0 or 5446 as `modelid_other_gender` (and modelid 5446 is alternate gender of modelid 3167 yet this is not reciprocal)

So, I suggest the following code:

``` SQL
UPDATE `creature_model_info` SET `modelid_other_gender` = 0 WHERE `modelid` IN (3257, 3258);
UPDATE `creature_template` SET `modelid2` = 0 WHERE `Entry` = 1642; -- Northshire Guard
UPDATE `creature_model_info` SET `modelid_other_gender` = 3167 WHERE `modelid` = 5446;
```

Are you ok with this for Guard Roberts? I'll look at the dwarf lady after.

**Comment by cala** [comment]
For the dwarf, @Tobschinski is right, there is obviously an error in setting other gender models. Here's my suggestion:

``` SQL
UPDATE `creature_model_info` SET `modelid_other_gender` = 0 WHERE `modelid` IN (1812, 4887);
```
