### ISSUE TITLE
Shade of Eranikus

### ISSUE THREAD

**Issue by TheTrueAnimal** [classicdb/database#710]
You should need to kill Jammal'an before being able to get infight with the shade of Eranikus. Four big drakes should help him infight, if nobody killed them before. 
At the moment you can always kill the shade of Eranikus an only one drake seems to help him.

Shade of Eranikus: http://www.wowhead.com/npc=5709/shade-of-eranikus
Jammal'an: http://www.wowhead.com/npc=5710/jammalan-the-prophet
Drakes:
http://www.wowhead.com/npc=5719/morphaz
http://www.wowhead.com/npc=5722/hazzas
http://www.wowhead.com/npc=5721/dreamscythe
http://www.wowhead.com/npc=5720/weaver

https://web.archive.org/web/20070304190158/http://wow.allakhazam.com/db/mob.html?wmob=5709

Dreamscythe should be hostile. At the moment he's neutral.

**Comment by cala** [comment]
Thanks for this report. I found several sources saying that Jammal'an is to be killed before Eranikus but none of them explains why. Is Eranikus beyond a gate ? Untargetable ? Despawned ? I don't know and back in Classic days, when I was running this dungeon, we always did Jammal'An before Eranikus so I never wonder what should happen if we try Eranikus first. Also, none of the videos I looked at show why Jammal'an is to be killed first (aside from spawning the two drakes in the main room).

Do you have any indication of what is supposed to happen if players try to kill Eranikus before Jammal'an, please?

**Comment by evil-at-wow** [comment]
@cala You can't attack him as long as Jammal'an the Prophet is alive. But he's always there (spawned) and you can even target him though.

It's Jammal'an the Prophet that is behind a force field - which is missing in TBC-DB, so perhaps it's missing in ClassicDB too - so you can't kill Jammal'an the Prophet without removing the force field first.

That explains the typical order in which players ran this dungeon:
- Clear the upper ring with the six troll mini bosses. Killing all six breaks the force field and provides access to Jammal'an the Prophet (and by transitivity, to Shade of Eranikus later).
- Killing Jammal'an the Prophet allows you to attack Shade of Eranikus, and also spawns Dreamscythe and Weaver. Morphaz and Hazzar are always spawned, so all four dragons are guaranteed to be spawned before you can engage Shade of Eranikus. If you don't kill them, the will come and help Shade of Eranikus when he's attacked.
- Actually, before Cataclysm **every** dragon on the floor was killed, and not just the four larger ones, because they all ran to Shade of Eranikus to help (and he was hard enough already at lower levels).

I'm pretty sure I have relevant sniffs somewhere, so I'll try to provide you with some data for the force field and the initial flags and so for Shade of Eranikus.

**Comment by cala** [comment]
Thanks  @evil-at-wow for this feedback, with lots of details, as always. :+1: 
The flags for Eranikus were the only parts I was missing. Now, I know what to look at.

The others parts either are already in Classic DB (like the force field) or pending an update I will push in a few weeks (and that I will gladly share with you).

**Comment by cala** [comment]
Closing this issue: it will be handled in SD2. Thanks everyone.
See PR https://github.com/scriptdev2/scriptdev2/issues/153
