### ISSUE TITLE
Pet Passive Hunters 1.12.1

### ISSUE THREAD

**Issue by e46ad** [classicdb/database#755]
Pet's not wanting to use ability's while in passive or defensive, I have to randomly press my abilty on my pet action bar in order to for the pet to use his spells,

Any one else have this issue out there seen this on a few servers.  

Classic DB Rel 20 Dev

Thanks for the

**Comment by e46ad** [comment]
??? Dev's ??? 

Can we get a reply to this ??

**Comment by cala** [comment]
No need to that impatient or pushy.

Remember that we are not Blizz, this is a _free_ project and we are working on it on our _free_ time. We have a job, a family and sometimes personnal issues to deal with, especially during the week, before fixing stuff for a ten years old game. And having most of the devs contributing to several parts of the project do not help.

If you think that your issue is more important than the 130+ other ones already opened and should be taken care of within two days, you are welcome to help fixing it by doing research, proposing (start of) a fix or whatever. 

It would be far more motivating and constructive than impatient and agressive comments. Remember: we are doing this on our free time and for fun.

**Comment by e46ad** [comment]
Lol impatient comments what are you talking about i asked for a dev to comment.

If you cant take criticism then don't ask people to report bugs to the forum.

And yeah i would say this issue "my issue" is quite high on the list. I never asked for a fix are you reading or just posting utter bull. I asked if any one knew about this.

Why would i work on mangos when people like you are so rude

**Comment by Tobschinski** [comment]
> ??? Dev's ???
> 
> Can we get a reply to this ??

Yep, thanks for you criticism, much appreciated.

**Comment by e46ad** [comment]
No problem dont ask people to list bugs if your going to cry like babies cos your failing to fix any of the 100 bugs listed. Thank you best of luck with this shit db now i know why mangos split haha

**Comment by Tobschinski** [comment]
Take care!

**Comment by krullgor** [comment]
i replied to you on the forum hours ago. core devs are not involved in db projects, so dont expect replies to obvious core issues here.

**Comment by Schmoozerd** [comment]
Did someone else notice, that posts containing keywords like "haha", "...","lol", and similar tend to be worthless?
(including this)

Happy weekend, best wishes and thanks for all the fish!

**Comment by e46ad** [comment]
EDIT : please, no bad words or swearing here.  /EDIT

Krullgor Thank you for the reply, I've read what you have said and will get back to you with a video etc soon cheers for the help.

**Comment by cala** [comment]
This really sounds like a core issue that can't be fixed by DB. Thanks Krullgor. I'm closing the issue here.
