### ISSUE TITLE
Incorrect start_time/end_time in game_event table due to use of TIMESTAMP data type

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#764]
Currently game_event TABLE uses TIMESTAMP data type for start_time and end_time columns:
TIMESTAMP has following problems:

1) It is 32-bit value and cannot get past year 2038. Not too imminent, but...

2) TIMESTAMP is stored as absolute time. If you have created binary database as part of repack and someone from different time zone uses this repack this person will have all times adjusted, i.е. incorrect. Worgen Curse event, for example, will start at completely different hour. Even using database yourself you will have +-1 hour adjustment in case of transition to/from daylight saving time.

This effect can easily be observed using command like
SET @@session.time_zone = '+08:00';
and viewing game_event table: start_time and end_time columns will change.

Much better solution is to use 64-bit DATETIME data type. It is local server time, so start_time and end_time columns will not change with time zone change.

https://dev.mysql.com/doc/refman/5.1/en/datetime.html

I tried following modification and found that everything seems to work correctly with it.

ALTER TABLE game_event MODIFY start_time DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Absolute start date, the event will never start before', MODIFY end_time DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Absolute end date, the event will never start after';

**Comment by evil-at-wow** [comment]
This should be changed in the core, because the game_event table is a core table, so it's the core that dictates the fields and their type.

I've been wanting to change this table and how it works for some time because of a second problem: the 'occurence' field (which is even misspelled because it should be 'occurrence') is not powerful enough. You can't schedule events like Darkmoon Faire properly for example, because it starts "the first weekend of the month" (or something like that). So sometimes that's four weeks after the previous one, sometimes that's five weeks. So now it just shifts...

**Comment by Neotmiren** [comment]
Yes, I also noticed limitations of `occurrence` field. To overcome them someone should provide .cpp patch to extend capabilities of event system.

TIMESTAMP to DATETIME change is much simpler, it requires only .sql update. DATETIME seems to be compatible with existing .cpp code.

**Comment by cala** [comment]
I'll handle the `start_time` and `end_time` columns type soon(tm) core side.
I fully agree on the limitation of the (mispelled) `occurence` field. I don't think this is much of a big change, but we need to define properly how we want to do it first.

**Comment by dagochen** [comment]
I think the most complex calculation is the darkmoon faire startdate. You could use negative occurence for core-side hardcoded calculations.
