### ISSUE TITLE
Alterac Mountains - Herbs

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#769]
The Alterac Mountains have too many herbs up at once.

**Comment by Tobschinski** [comment]
![238964-pokemon_yellow_gameplay_super1](https://cloud.githubusercontent.com/assets/4753528/7814588/68c67c1a-03c3-11e5-8d65-3bad73c1a3b2.jpg)

**Comment by Tobschinski** [comment]
![238964-pokemon_yellow_gameplay_super1](https://cloud.githubusercontent.com/assets/4753528/7814642/ad065382-03c3-11e5-9375-001532b8d49a.jpg)

**Comment by cala** [comment]
Given the hit point of the Tobschinski pokemon, I'm afraid using the Cala ability will do you more harm than good if it fails (and it often fails).

**Comment by cala** [comment]
Hopefully fixed in https://github.com/classicdb/database/commit/4dc8e13020f63b9427fd08c49dfd5c3ef2bdc3c5

I updated the resources pool system by adding a finer density management for the herbs.

It should result in more spawns in starting areas (where they were a bit missing) and less spawns in zones with lots of nodes like Alterac Mountains. However, it will still be impossible to balance zones like Azshara where one part has many spawn points sniffed (like the western areas) while other part is poorly sniffed (northeastern area).
