### ISSUE TITLE
Various problems in Dire Maul

### ISSUE THREAD

**Issue by Schmoozerd** [classicdb/database#77]
Reported here: https://github.com/scriptdev2/scriptdev2-classic/issues/9
Most are clearly DB related.

I hope you guys will be able to resolve some of them.
Quite possible that the best cause of action would be to copy all spawns from udb, and copy all further pending things (templates, _addon, movement, scripts, etc..) pending.
Not sure how such a step can be performed most effectively, but it might be interesting to go for it.
(Ideally would be if you could be able to keep guids 1:1 between udb/classicdb)

**Comment by Schmoozerd** [comment]
A few more (some the same?) bugs mentioned here:
https://github.com/scriptdev2/scriptdev2-classic/issues/5#issuecomment-22074524

**Comment by cala** [comment]
I agree that a massive backport from UDB would be the best solution but as you said, it will need some preparation to mininise the amount of work (and errors).

Like I did for the pools spawns and when it is possible, I try to keep as much ascendant compatibility as possible between classic DB and TBCDB/UDB. :)

**Comment by Schmoozerd** [comment]
Actually, UDB was reworked on DB side a few years ago.
But it appears NF was a bit drunk while doing so and the quality of DM in UDB is also not too great..

On the good side we have good resources for MD from 333 - maybe you can speak with @crackm if he is willing to run the stuff through his improved parsers and diff it to UDB and prepare some improvements there first.

(Though changes in this freaking instances will require extra manual work and control..)

These many events tend to screw parsed stuff :(

**Comment by cala** [comment]
Good to know. I will contact @crackm shortly about these resources you are speaking of. As the instance was barely changed between Classic and WotLK, I assume I can do the manual work and check on the data if @crackm is willing to parse them with his tools. Then, porting the results to UDB or Classic DB would be roughly the same.

**Comment by cala** [comment]
Copy/paste of whole initial report from @raymerjacque
I opened some dedicated issues.

NPC/Event/Quest/instance script.
- [x] Immol'Thar's prison does not have the forcefield around it, therefor it is not necissary to clear the pylons/beacons.
- [x] Lord Hel'Nurath is always spawned, while he is supposed to be summoned.
- [x] Prince Tortheldrin is spawned hostile, while he is supposed to be turned hostile by talking to him or slaying Immol'Thar.
- [x] Quest: "Elven Legends" is incompletable; nothing happens when you click on the skeletal remains of Kariel Winthales
- [x] Ancient Equine Spirit should only appear after you've killed Tendris Warpwood, now you don't have to kill him, making the paladin mount quest really easy.
- [x] The treant mobs in the capital gardens should be walking around, so that you can't skip them so easily.
- [x] If you aggro Tendris Warpwood, all the Ironbark Protector mobs in the capital gardens should come and help him in the fight, so you should need to kill those first. But the aggro isn't linked now.
- [x] All the pylons in DM west are missing. (I can show you the location of these.)
- [x] "Ironbark the Redeemed" shouldn't be spawned at the Capital Gardens.
- [x] "Ironbark the Redeemed" shouldn't be hostile, he should be friendly.
- [x] Missing trap at guard Slip'Kik, in order to perform a tribute run, you would have to freeze guard Slip'Kik using that trap, thus making it able to skip him.
- [x] Missing NPC spawned after killing King Gordok; Mizzle the Crafty.
- [x] The Gordok Tribute chest is already spawned, while it is supposed to be spawned by Mizzle the Crafty. When spawned, the containments of this chest is supposed to rely on what DM north bosses you have spared on your way to the king. On VG, the contaiment is random.
- [x] Missing buff: Gordok King. This is also given to you by talking to Mizzle the Crafty.
- [ ] Performing a "tribute run" is imposible due to the bugs above.
- [x] The doors in DM north don't require keys to open them.
- [x] Pussilin, the first NPC you can see when you enter Warpwood Quarter. He should be friendly at first, and you should be able to talk to him. Then he would run, and a chase would begin, leading you all the way to the end of the instance, and then, when you talk to him for the last time, he should turn hostile, spawn "Wildspawn Imps" (about 4 of them) However, he is killable from the start, making the quest: "Pusillin and the Elder Azj'Tordin" impossible to finish. Pussilin also drops the kew that opens the doors to DM west and north. (the doors that are missing)
- [x] After you've killed the boss: "Zevrim Thornhoof", "Old Ironbark" should change to "Ironbark the Redeemed" He would open the door that leads to Alzzin the Wildshaper. But the door he is supposed to open isn't there.
- [x] Isalien is supposed to be a spawned boss for a quest in the T0,5 quest chain, but she's there already.
- [x] Isalien should spawn a hostile pet "Empyrean" about 10 seconds in the fight. However, now she spawns Empyrean immediatly after she's pulled.
- [x] The class specific books to get: "Royal Seal of Eldre'Thalas" and the book: "Foror's Compendum of Dragonslaying" are supposed to drop from any boss in eather west, north or east. On this server it only drops from Guard Slip'Kik.
- [x] The Shen'Dralar mobs are attackable, they shouldn't be.

http://www.wowwiki.com/Immol'thar
http://www.wowwiki.com/Lord_Hel'nurath
http://www.wowwiki.com/Prince_Tortheldrin
http://www.wowwiki.com/Dire_Maul_tribute_run
http://www.wowwiki.com/Guard_Slip'kik
http://www.wowwiki.com/Mizzle_the_Crafty
http://www.wowwiki.com/Gordok_Courtyard_Key
http://www.wowwiki.com/Gordok_Inner_Door_Key
http://www.wowwiki.com/Pusillin
http://www.wowwiki.com/Quest:Pusillin_and_the_Elder_Azj'Tordin
http://www.wowwiki.com/Old_Ironbark
http://www.wowwiki.com/Isalien

**Comment by cala** [comment]
@Schmoozerd I tried to fix one of the issue reported above: 

> "If you aggro Tendris Warpwood, all the Ironbark Protector mobs in the capital gardens should come and help him in the fight, so you should need to kill those first. But the aggro isn't linked now."

With the following code:

``` SQL
-- Added aggro link between creature 11459 (Ironbark Protector) and creature 11489 (Tendris Warpwood)
DELETE FROM `creature_linking_template` WHERE `entry` = 11459 AND `map` = 429;
INSERT INTO `creature_linking_template` (`entry`, `map`, `master_entry`, `flag`, `search_range`) VALUES
(11459, 429, 11489, 1, 50000);
```

I chose to use the `creature_linking_template` table instead of the other one as all the related creatures are in the same map and are concerned. I also thought it cleaner than using a dozen of guids entries.

However, when engaging Tendris Warpwood (11489), the other NPC never come to its help. So I wonder if I missed something or if there are some limitations as the linked NPCs are very far on the map (hence the 50000 radius)?

**Comment by Schmoozerd** [comment]
use 0 as radius (which means everywhere)

did you engange normally or unnormal (like with .dam command)
It should work this way, though.

**Comment by cala** [comment]
Thank you for this answer.

And I engage it normally: moving close to it until it aggroes. I was afraid the linked NPC would not aggro because they were too far on the grid to find a target, path to the target or even unloaded from the grid.

I will try this new value this WE.

**Comment by TheTrueAnimal** [comment]
I'm a noob but i hope this might help:

Added waypoints of creature 14323 in Dire Maul North
UPDATE `creature` SET `MovementType` = 2, `position_x` = 473.034, `position_y` = 588.591, `position_z` = -25.404 WHERE `guid` = 138187;
DELETE FROM `creature_movement` WHERE `id` = 138187;
INSERT INTO `creature_movement` VALUES
(138187, 1, 473.034, 588.591,-25.404, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 2, 483.548, 602.538, -25.404, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 3, 522.537, 592.233, -25.402, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 4, 562.265, 588.980, -25.402, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 5, 558.045, 544.167, -25.401, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 6, 481.622, 542.984, -25.373, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 7, 558.045, 544.167, -25.401, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 8, 562.265, 588.980, -25.402, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138187, 9, 482.777, 576.748, -25.404, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),

Sources:
https://www.youtube.com/watch?v=42ZpEp9_-TE
https://www.youtube.com/watch?v=TRaI91-6kO0

Added waypoints of creature 14321 in Dire Maul North
UPDATE `creature` SET `MovementType` = 2, `position_x` = 385.883, `position_y` = 342.841, `position_z` = 2.862 WHERE `guid` = 138186;
DELETE FROM `creature_movement` WHERE `id` = 138186;
INSERT INTO `creature_movement` VALUES
(138186, 1, 385.883, 342.841, 2.862, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 2, 296.831, 338.605, 2.852, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 3, 475.419, 338.564, 2.851, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 4, 385.883, 342.841, 2.862, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 5, 388.354, 259.012, 11.439, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 6, 440.744, 256.109, 11.207, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 7, 287.014, 255.112, 2.859, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 8, 291.174, 202.809, 2.852, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 9, 291.128, 329.944, 2.851, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 10, 287.014, 255.112, 2.859, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(138186, 11, 388.354, 259.012, 11.439, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

Sources: 
https://www.youtube.com/watch?v=wKS2oOc3J7E (8:55)
https://www.youtube.com/watch?v=vve0aB4uAq8 (2:25)
https://www.youtube.com/watch?v=yFAEbbo3VlA (7:10)
https://www.youtube.com/watch?v=KwBMEEfM5FU (2:22)
https://www.youtube.com/watch?v=zmFxUD4HipI (0:43)
https://www.youtube.com/watch?v=PecPLu8SgfQ (4:30)
https://www.youtube.com/watch?v=DrVy1TFizfk (5:06)

**Comment by evil-at-wow** [comment]
@TheTrueAnimal Your efforts are surely appreciated, and this looks helpful. I'm guessing @cala would have one remark here though: if the creature only has one spawn, we usually use the template variants of tables where possible. So in this case, you should use creature_movement_template instead of creature_movement.

Having that said: don't worry too much about the waypoints in Dire Maul, especially if you don't have sniffs to get 100% accurate data. You're most likely not aware of it, but I'm respawning the three Dire Maul wings from scratch with offi data. The East wing is mostly done, and @cala has added it some time ago. The other two wings are in progress but I need to fix a few core issues first before I can continue. So it'll take some time to finish, but I promise you the results will make it worth the wait!

Again: your efforts are appreciated. If you really don't want to wait a few months and want to continue making a few improvement in the meantime, as a learning experience or for some other reason, you're of course welcome to do so. I'm just trying to make sure people aren't needlessly doing double work :smile:

**Comment by cala** [comment]
AI script for Isalien (spawn time of its add) is fixed. A pull request was made to ACID regarding that: https://github.com/ACID-Scripts/Classic/pull/13

**Comment by cala** [comment]
Last parts remaining open are fixed by: https://github.com/classicdb/database/commit/94a05ca598dc32a62d531aa43f4ae831511afda4 and https://github.com/classicdb/database/commit/225f7272e1fc3dfd4a8dd29f2c8fecc26b03615a
