### ISSUE TITLE
Wrong model/voice combination in modelid 7311 (one of Protectors of People, Westfall)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#785]
``` sql
UPDATE creature SET modelid=7310 WHERE guid=90391 AND modelid=7311; -- 7311 is invalid: has female voice, but male in looks
UPDATE creature_model_info SET modelid_other_gender=0 WHERE modelid=7310; -- disable use of 7311 as alternative to 7310
```

**Comment by cala** [comment]
Thank you for your report. The problem is a bit different, the model is ok but it is set with the wrong gender. This is why it is using the wrong voice gender. Also one of the possible alternate type for this NPC will never be used in the current DB state.

This is another example of wrong model backports from TBC/UDB to Classic. I already had to fix a lot of those for UBRS or Horde NPCs.

I'll push a fix soon.

**Comment by Neotmiren** [comment]
What do you mean by "model is ok but it is set with the wrong gender"? Where is it set wrong? In DBC files (model is not ok in this case) or in SQL DB? Do you think it is possible to use model 7311 somehow?

By the way, this issue is quite old - exists in MangosZero (2011/2012) repack as well.

**Comment by cala** [comment]
My mistake, there's indeed an error in the DBC file. My previous post was made on DB analysis alone which is also wrong.
