### ISSUE TITLE
Quest: Garments of the Light (Alliance)

### ISSUE THREAD

**Issue by scotty0100** [classicdb/database#788]
Cannot complete the priest quest "Garments of the Light" in Goldshire because Guard Roberts is not heal-able.

**Comment by cala** [comment]
Thanks for this report. I tested the day before yesterday the UD quest, similar to this one (it uses the same SD2 script) and it worked. On SD2 repository, there is already a pull request/discussion about Guard Roberts: https://github.com/scriptdev2/scriptdev2-classic/pull/44 and apparently, the NE quest also works. This looks like this is related to PVP flag and that only Guard Roberts is not working.

Looking at the DB, the only difference I can see is that Guard Roberts is flagged as Civilian while other injured guards are not. Civilian was a specific PVP flag back in Classic to prevent players from chain kill specific NPCs by granting them Dishonorable Kill. Guard Roberts was not a civilian, so at least this needs to be fixed.

Could you try please:

``` SQL
UPDATE `creature_template` SET `Civilian` = 0 WHERE `Entry` = 12423;
```

I don't know if this will fix the quest, but that's the only idea I have in mind right now.

**Comment by Tobschinski** [comment]
Change Robert's faction and the quest will work. No idea why ...

**Comment by cala** [comment]
I remember that this NPC previously had faction = 11 (Stormwind) and that he was chain killed by nearby wolves NPCs. We changed his faction to 12 (like in all other DBs) and that fixed the problem... only to make a new one.

The fixed provided in the SD2 PR is working with no side effects. So I prefer avoid modifying the DB values, especially since they seem to be correct.

**Comment by Tobschinski** [comment]
I don't want to argue about the faction, I know it is correct. However, changing it will make the quest completable.
