### ISSUE TITLE
Class Paladin / Mage - Classlevelstats

### ISSUE THREAD

**Issue by Tobschinski** [classicdb/database#790]
Redo the basedamage and armor for all mages,  it cannot be correct.

Redo the armor for all paladins, does not seem to be correct.

**Comment by cala** [comment]
As you know, I'm fixing the trash mobs stats in BRD and I thought the same as you with the few mage NPCs that are there. But I did not dig it up more.

I took a few minutes to plot the base armor of warrior, paladin and mage versus level for Classic, TBC and WotLK cores based on the base stats in Classic DB, TBC-DB and UDB and the results are shown below:

![Classic base armor versus level](http://img11.hostingpics.net/pics/581371statsclassic.png)
![TBC base armor versus level](http://img11.hostingpics.net/pics/742081statstbc.png)
![WotLK base armor versus level](http://img11.hostingpics.net/pics/594486statswotlk.png)

Several things strike me:
1. In Classic and WotLK Paladin and Warrior have basically the same base armor values, the differences are very small in comparison of the armor value. For example, the base armor of a lvl 65 warrior is 5234 while Paladin is 5228. This is a 6 point difference, roughly 0.2% of the value. In TBC, at the same level, the base armor difference is basically 20% of the warrior armor value. 
2. When visually comparing Classic graph versus TBC graph, it looks like Classic's warrior graph and TBC's warrior graph are roughly the same (same range, same curves), which seems logical. But stranglely, it also looks like Classic's mage graph is following the same curve than TBC's Paladin graph and more strangely that TBC's Mage graph is "missing" in Classic graph (since Classic mage graph is where Paladin is expected to be, based on TBC curves).
3. Armor values are exactly the same in Classic and WotLK for Warrior, Paladin and Mage up to level 65. Why would they be the same when they are different in TBC?

Before digging further, it would be nice to have @X-Savior and/or @cyberium opinion on the matter since they worked on the stats system and that @X-Savior filled the level stats tables with these data. Maybe, they could explain us how the values were calculated, with what sources and why they are that way. :smile:

**Comment by X-Savior** [comment]
Hey guys,

Tobi just directed me to this.

We can have discussions on this.... but I know Armor has not changed between all 3 expansion packs. They are set values for each level regardless of Expansion Value the NPC is. These values are from Sniff Data and are 100% correct.

**Comment by X-Savior** [comment]
Looks like there was a screw up on the ClassicDB commit.

I have provided Tobi with correct data...

I am SO SORRY guys :(  (Too many versions of the file floating around back then).

**Comment by cala** [comment]
> We can have discussions on this.... but I know Armor has not changed between all 3 expansion packs. They are set values for each level regardless of Expansion Value the NPC is. These values are from Sniff Data and are 100% correct.

I remember discussing this with you when you were working on those data and you explained to me how they were calculated and checked. Thus, we had no reason to doubt them. That's why we were surprised by the results shown above and we wanted to have your thoughts on those.

I read (later) the IRC discussion between @Tobschinski and you. So if I understand you correctly:
- base armor values were unchanged from Classic to WotlK. Since those in TBC-DB are ok (they compare nicely to the Bestiary) we could safely use them for Classic.

Regarding others points you discussed on IRC:
- UDB has the exact same data than Classic DB (at least for armor). So if Classic DB data are wrong, chances are good that UDB data are also wrong
- Adding a description field to the various `*_loot_template` tables is a very good idea. We should have done so long ago! :+1:

**Comment by Tobschinski** [comment]
to check

Warrior 12
Warrior 28

**Comment by Tobschinski** [comment]
https://github.com/TBC-DB/Database/commit/a74bb53d4d12526ec9750b1a8562120c33552432

**Comment by cala** [comment]
@Tobschinski if you agree with this, I will backport in the coming weeks armor data from TBC-DB so we can mve on with this.
If you have any value/class/level you would like to check first, please let me know.

**Comment by Tobschinski** [comment]
Nah, none of the armor values listed in the Bestiary really fits flat multipliers. I have no idea why but I do not plan to check anything right now.

**Comment by cala** [comment]
I remember that you have exams soon or even now, so no worries. I'll see if I can come to something by myself or if it will have to wait a bit longer. :smile:

**Comment by cala** [comment]
Fixed by https://github.com/cmangos/classic-db/commit/ee13a55c377da3941ee01c56109e4e610f7d225d
I can't promise that every single value is correct but statistical analysis against the bestiary shown they should be.
