### ISSUE TITLE
Sapphiron 2

### ISSUE THREAD

**Issue by Kelzior** [classicdb/database#811]
Only 4 people can go trough portal to Frostwyrm Lair

**Comment by cala** [comment]
The issue is fixed?

**Comment by evil-at-wow** [comment]
@cala Unlikely, but who knows. I've noticed our reporter here has the annoying habit of closing issues without further comments if they are not fixed fast enough to his/her liking. At least that has happened on quite a few occasions in the core...

**Comment by Kelzior** [comment]
Yep wasting time here

**Comment by cyberium** [comment]
In 12 month you was able to :
- provide a more complete description with videos/images/sources etc...
- learn sql to help contribute
- learn c++ to help contribute
- learn github to help contribute
- learn to be kind
- fix this yourself as its "simple" issue

So yes you are wasting our time here as you are not able to understaind that we work on this when we have time and we work on what we prefer.

Goodbye.

**Comment by Kelzior** [comment]
You may be right but I already did help you guys fixing major crashes that were existing for years

**Comment by cyberium** [comment]
Never said you didnt help but only you are not enough patient to let devs find a time to work on it or brave to fix it yourself.
Any issue posting is a help.
There are issues posted long time before yours.
Probably not closed because too hard to fix or, no current devs are interested, or too much time consuming or....
But knowing that issue exist is anyway a help.
