### ISSUE TITLE
InstallFullDB.sh: line 116: [: too many arguments

### ISSUE THREAD

**Issue by Enverex** [classicdb/database#831]
I'm not sure it's parsing the check properly here. The script breaks trying to do updates with...

```
Process classic database v1.6.5 'The Wailing Pet, The MidSummer Joy and all that sort of things'.
Process database updates
./InstallFullDB.sh: line 116: [: too many arguments
   process update updates/1319_creature_template.sql
```

With like 116 being...
`if [ ! -e ${ADDITIONAL_PATH}updates/[0-9]*.sql ]`

That said, it still says "process update..." for each file in that folder so despite the error in the above check, it does still seem to do the patching for each SQL file.

**Comment by cala** [comment]
Thanks for your report. I often have the same error message. However, the installation processes as expected. Moreover, the error message does not seem to occur on other installation steps using the same command. So I suspect, there are some wild character or formatting on that specific line that is not appreciated by the shell. Which shell are you using, please?

**Comment by Enverex** [comment]
My machine is using Bash, although I ran the script via "./scriptname" so whatever the script has as its shebang would have been used (which I assume was bash).

**Comment by katz1** [comment]
I've experienced something similar on my Debian 8 server which uses bash:

```
Process classic database v1.6.5 'The Wailing Pet, The MidSummer Joy and all that sort of things'.
Process database updates
./InstallFullDB.sh: line 116: [: too many arguments
   process update updates/1319_creature_template.sql
   process update updates/1320_quest_template.sql
   process update updates/1321_quest_template.sql
   process update updates/1322_creature_template.sql
   process update updates/1323_dbscripts_on_quest_start.sql
Updates applied
```

**Comment by foreversnoopy** [comment]
Same issue here. Running debian jessie in a docker container. Code is up-to-date.

I run the script with "./InstallFullDB.sh".

From what I understand, there's no problem and everything is updated correctly ?

**Comment by katz1** [comment]
I just looked into this. Yes, everything is updated correctly despite the error.

I made a pull request for this, hope someone can review it and test it on Windows as well.
 #837

**Comment by cala** [comment]
Thanks @katz1 for researching the cause of this issue.

In a nutshell:
- before applying the updates, the script checks if there is at least one update file to apply, using a regular expression pattern
- if there is none, it displays a message and goes on
- if there is more than one update files, the check raises an error because it can only accept 1 argument (and got as many as there are matching files. But the script still goes to the update loop because there is at least one update file returned. Then, the updates are proceeded as intended

So, the Installation script works, despite an error message which is more a warning than a real error in our case.

**Comment by katz1** [comment]
Thanks for the review @cala 
Actually, I did not meant that second part to be committed because it was not strictly related (it was an accidental commit to that branch). And I believe there was a mistake in it, but you spotted it fortunately. Just to be clear, the reason behind the second change is the following:

If you set up the CORE_PATH to an incorrect **but existing** path, the script will give the following result:

```
Applying additional core updates from path ../mangos-classic/sql/updates/

./InstallFullDB.sh: line 176: [: z*_*_mangos_*.sql: integer expression expected
All core updates applied
```

The second part will change this to a more meaningful message. I intentionally included the path in the message to potentially make someone realize that they setup the CORE_PATH incorrectly.

I think it is fine the way you committed it as well.
