### ISSUE TITLE
Scholomance mobs to despawn.

### ISSUE THREAD

**Issue by Vanillafanatic** [classicdb/database#832]
The trash in the room that contains the chest (The gated chest which is accesed by a lever in Jandice barovs room) And also is the entry to the viewing room. Alot of that trash would be despawned after killing Rattlegore. As of now. this room is quite deadly without this happening.   

Before rattelgores death   https://www.youtube.com/watch?v=m-JZbeJeYX0

https://youtu.be/VAWFsYprkhk?t=559    <-- whats left after.rattlegores death.

Maybe blizzards original way of hinting 'Hey dummy, this isn't the solution to die in here!'

**Comment by evil-at-wow** [comment]
I believe you are comparing different things here. The second video is clearly made during Cataclysm, when Scholomance was reworked significantly and moved to a different level (for low 40 players). A lot of the trash was removed when this was done, similar to what they did in Dire Maul. As far as I know, killing Rattlegore has never despawned any trash.

Actually, the room you're referring to was recently respawned by @cala with data from the original instance, so it should be almost perfect now spawn wise. But I agree that it is probably harder than intended now because you can pull more than intended. There seems to be an aggro range problem in the core - see #716 for details.

**Comment by Tobschinski** [comment]
Where is the 2nd Necrofiend in that TBC-video ...

**Comment by evil-at-wow** [comment]
I believe there was no second Necrofiend in the original Scholomance. I have several sniffs from the WoTLK era - so before the Cataclysm revamp of Scholomance - and they are all consistent in that there's only one patrolling Necrofiend. They nerfed it hard anyway by removing four groups of trash and only leaving the ones in the corners, so they probably added one additional Necrofiend to make the room look somewhat filled...

**Comment by Tobschinski** [comment]
Which is weird, because of [this](https://www.youtube.com/watch?v=CtZftE1lUPU&feature=youtu.be&t=134) - Uploaded on Sep 28, 2009

Or have a look at [this video](https://www.youtube.com/watch?v=gMZuxi9lfYg), when he first jumps down, the room is crowded. Though, after killing Rattlegore, most of the groups are gone.

Or what about [this](http://wow.allakhazam.com/forum.html?forum=21&mid=117128121014578838#8) post, [this](http://wow.allakhazam.com/forum.html?forum=21&mid=11460153628443222) thread ...

I call black magic.

**Comment by evil-at-wow** [comment]
Hmm, interesting, so changes to that room seemed to happen after all. I've never noticed really, but it means that I should find evidence in sniffs then...

**Comment by Vanillafanatic** [comment]
Careful with the use of wotlk sniffs, alot of mobs were removed and changed to suit rdf. especially in dire maul west.

**Comment by evil-at-wow** [comment]
It's usually not that bad, because LFD was introduced in patch 3.3 and the data I'm talking about predates patch 3.3. So at least it's data from an era where Scholomance was still the original dungeon you had to go to yourself at the end of Classic (as far as I know).

That said, I do agree with you that we should take every single bit of data with some salt if it's not coming from a sniff with a matching version.

**Comment by cala** [comment]
Hi,

Thank you for bringing this topic.

A few words on this:
- I don't remember the mobs in that room (the one right before the Viewing Room) being rearranged in any way. From initial release to TBC, I did countless times the instance the usual way (killing Rattlegore first) and also a couple of times with one of us already having the key, thus skipping Rattlegore. However, I may be wrong since I always played a ranged class in Scholo, meaning I never saw the "full room" in both conditions. So any hints from @evil-at-wow would be welcome and I would add it (from DB or more probably in SD2)
- I indeed remade that room in https://github.com/classicdb/database/commit/bc0a7a9e0c082d6262aca7c7779e4cf71a7bba3a and I tested it with a five-man group before and after the fix and the post-fix is do-able, while the pre-fix would result in half the room being pulled: wipe assured. So, the current DB state is far closer to the vanilla retail state than it was (and probably is in other open source DBs out there)
- I agree that fixing for a given patch with data coming from another version is not perfect. Yet, when done carefully (_i.e._ knowing what changed can possibly have occurred between the two versions), one can have pretty good results, at least far better than the manual positioning that is so often encountered in dungeons for most DBs. And I trust @evil-at-wow on that matter: his brain seems to keep track of every possible version of the game. :tongue:

**Comment by Phatcat** [comment]
Have we met? I'm Phatcat and I research the shit out of things. Let me just force myself onto this one.

**https://www.youtube.com/watch?v=_E4rSiwYMGM**
There is a quick beautiful snap of most of the room pre- Rattlegores death in this video by 2:17/2:18
This does not look like 4 groups, but more the 'mass' we currently have set up in the DB. Indicating we may be very close to how initial spawns in the room should be set.

**http://wowwiki.wikia.com/wiki/Scholomance_%28original%29/stealth_run?oldid=346838
"Viewing Room Door
1. Stealth back to the area below A, where the mobs are now in 4 groups, with 2 Crypt fiends patroling."**
Especially pay notice to the wording of '**are now**', as well as '**2 Crypt fiends**' obviously stating that they were arranged differently earlier, and that there should be... ahem... 2 friendly spiders.

**_So yes. They rearrange, and the fiends start patroling._** (maybe also spawn a second fiend, if only 1 should be spawned on instance creation)

**https://www.youtube.com/watch?v=T4g8nnx69RY**
Around _15:44_, notice the amount of mobs in the room when he does the pull - if they had done more groups from that room beforehand their bodies would be all over the place, yet we only see the patroling fiends body at _15:50_. Also, the group he pulls is hugging the shit out of that corner, wouldn't you agree?

**https://www.youtube.com/watch?v=d85xDraICrs**
Also shows the wall hugging of groups in the room before the viewing room from about _4:47_ and on.

**Comment by evil-at-wow** [comment]
@Phatcat  I don't know if we've met before, but at least I've noticed you on github before! Thanks for the research and efforts above.

I believe many of us are convinced by now that killing Rattlegore made changes to that room at least at one point in time, even though some of us - myself included - never really noticed this while playing back in the days.

As I said earlier, the interesting thing here is that @Tobschinski has linked to a video from WoTLK suggesting this change too (the first video he linked), and it so happens that I have some WoTLK Scholomance data...

And so I went digging. And behold: I have found convincing evidence of what has been suggested! My original analysis of the room in the other issue - 33 spawns as one patrolling Necrofiend and eight groups of four - still holds of course. So your respawning effort was not in vein @cala, because it's the correct initial state of that room. But in the data of an almost full clear (skipping just Jandice Barov) I also found a set of different spawns in that room. During my analysis last year I seem to have dismissed these as respawns because I couldn't explain them otherwise (I found a note I made about them). After all, it took us a while to clear the dungeon and these spawns had higher IDs, meaning they were spawned after everything else. So despite seeing less spawns, and despite the new spawn positions not matching exactly with the original ones, the conclusion I made was the best I could do at the time I guess. But I know better now: the 17 new spawns I found is exactly what I'm expecting when I see those videos. They seem to be the four groups of four + one additional Necrofiend we're looking for. I'll post their data soon after a few additional checks, and I'll also try to verify these spawns are happening right after Rattlegore's kill.

**Comment by Tobschinski** [comment]
Please also check your sniffs if Rattlegore spawned a spider on my ceiling.

**Comment by evil-at-wow** [comment]
Further analysis revealed that the packet with the new spawns is indeed sent immediately after Rattlegore's death, so I think we can confirm the theory of the room's rearrangement. At least I'm fully convinced now.

The spawn data for the new spawns follows. For what it's worth, the four new groups seems to follow the rules I outlined in the other issue as well. That is, each of these groups has exactly 2 Risen Aberration (10485), most likely at any two random spawn points in the group, and the remaining two spawn points in a group were either a Diseased Ghoul (10495) or a Reanimated Corpse (10481), with one always being a Diseased Ghoul and the other being a Diseased Ghoul or Reanimated Corpse with a 50/50 chance for each.

| X | Y | Z |
| --- | --- | --- |
| 186.036 | 94.5 | 104.715 |
| 179.117 | 95.5166 | 104.8 |
| 180.612 | 100.176 | 104.798 |
| 185.926 | 100.079 | 104.798 |
| <br> | <br> | <br> |
| 178.999 | 75.2952 | 104.716 |
| 185.558 | 77.276 | 104.715 |
| 187.556 | 70.4334 | 104.716 |
| 180.51 | 82.3917 | 104.716 |
| <br> | <br> | <br> |
| 212.915 | 70.6005 | 104.798 |
| 221.199 | 77.0037 | 104.715 |
| 214.381 | 76.233 | 104.798 |
| 218.64 | 71.5957 | 104.715 |
| <br> | <br> | <br> |
| 221.249 | 94.9361 | 104.715 |
| 214.406 | 101.903 | 104.715 |
| 217.521 | 95.4237 | 104.715 |
| 223.296 | 105.101 | 104.715 |

In addition to these four groups, there is an additional Necrofiend spawn that is using waypoints. So far I have not found complete data for this addition patrol in my sniffs, but the most complete path I have found has 5 waypoints that are matching exactly with 5 of the 8 points of the path I posted for the initially spawned Necrofiend (see #716). So it's very likely they are sharing the same waypoints, especially because the matching points are points 6, 7, 2, 3 and 4 in that order, with a 35 second gap with no movement info in my sniff between points 7 and 2 (which I'm guessing is related to my character being too far away from the action because it was running back from Rattlegore's room to that room). The second Necrofiend seems to spawn at point 4 though. Also, I have not found any evidence (yet?) of the initial Necrofiend respawning or moving positions when Rattlegore dies, so for all I know you might end up with the second Necrofiend spawning on top of the first one if you're unlucky.

@Tobschinski I'm sorry, but I can't confirm that killing Rattlegore spawns spiders on your ceiling. Then again, I don't seem to have any data from a Scholomance run done on Friday the 13th where during the Rattlegore fight a warlock managed to kill all present mages as a nice side effect, so who knows what evidence we might find later!

**Comment by cala** [comment]
Thank you very much @evil-at-wow for these data! I will add this to Scholomance soon. This should be doable from DB only, but that would require to use heavily the evilish GUIDs, so I think a SD2 approach would be more proper here.

**Comment by Tobschinski** [comment]
Hm, the path the second necrofiend moves on looks different though:
![untitled](https://cloud.githubusercontent.com/assets/4753528/15085905/884029f8-13dd-11e6-828a-7f73a0514887.png)

Maybe it is truncated to not lead to the unlucky situation with stacked spawns?

**Comment by Tobschinski** [comment]
Nope, just nope: https://youtu.be/VAWFsYprkhk?t=561

I'm glad that is out of the way! Fire that cutter for his unfortunate work.

**Comment by cala** [comment]
So, the path sniffed by @evil-at-wow for the second Necrofiend is the full path, not a part missing some of the point?

**Comment by evil-at-wow** [comment]
Indeed, I believe the conclusion is that both Necrofiends have the same path.

@Tobschinski wasn't convinced initially because of the positions in the above screenshot. But that's a good thing actually, because challenging data and theories often leads to more and better research, which eventually leads to a better understanding and thus better server!

**Comment by cala** [comment]
Ok, thanks for the feedback. I had this to the few SD2 patches I will do soon(tm).

**Comment by cala** [comment]
Ok, working on this script right now.

I just have one last question and would like to have your opinion on the matter as I'm afraid we will never get the answer: what happen if the players already start to kill some mobs in the room and then kill Rattlegore? My opinion is that beyond a given treshold of killed mobs, the respawning of the room should not occur as it would be meaningless. I would set such a treshold to 50% (because it is basically what the respawning does: it removes 50% of the total NPCs: 8 groups, then 4). What are your thought on the matter?

**Comment by Phatcat** [comment]
The thing is that it is not just the amount of mobs, it is also the placement that seem important. Some parties may go kill half the room, but the other half of the room could be left placed really badly. I think it's important to reset the whole room nomatter how many in the pre-viewing room have been downed. Just my thoughts =)

**Comment by cala** [comment]
Clossed by https://github.com/cmangos/mangos-classic/commit/3e6fed71dc549d70e27abe82162809dd956711c1
Thanks everyone. :+1:
