### ISSUE TITLE
Astor Hadren displayed HP

### ISSUE THREAD

**Issue by katz1** [classicdb/database#847]
Astor Hadren (6497) is an NPC you face as an undead rogue in the quest 1886.
He is neutral initially, and turns hostile after you speak with him.
After he turns hostile, his HP bar drops to around 1/3 of total. He still seems to have the right HP, because that 1/3 of HP is pretty hard to beat down, so only the displayed HP ratio is wrong after he turns hostile.

**Comment by cala** [comment]
I'm pretty sure this is a core issue related to the fact that the NPC 6497 is friendly to you at first (its hit points values are displayed). Then, it turns hostile and the core must hide the values to you, only displaying a percentage of it. There is possibly an error on what is sent to the client in that case.
Poking @cyberium on this because he wrote the related patch.

Also the DB script for this quest is poorly made, but this is unrelated to the issue.

**Comment by cyberium** [comment]
confirm i will look at it you can close this and open a core issue.

**Comment by cala** [comment]
Issue opened in core https://github.com/cmangos/issues/issues/952. I'm closing here.
