### ISSUE TITLE
Ubrs (Blackrock Stadium)

### ISSUE THREAD

**Issue by Vanillafanatic** [classicdb/database#849]
When the rend event starts, Orcs  are meant to spawn up ontop of  the west platform.  (No, not nefarions side, the other) This stops people leaping into arena event once its began.    

https://youtu.be/ZVW5nwTpSpE?t=31  
https://youtu.be/NJZswzneYyg?t=263

Someone with unlimited internet can youtube further. =P
 I cannot remember if they spawned and walked to the edge, or just spawned, but any improvement here would be a start.

**Comment by evil-at-wow** [comment]
I'm fairly sure they don't just spawn, but spawn "outside" and run into the arena area. I might even have sniffs somewhere to prove it, but I'll have to check first before I make any promises.

**Comment by Tobschinski** [comment]
Bitch please, even I got one this time...

**Comment by cala** [comment]
Then, I promise all my eternal love and admiration for the first of you that can share those spawn data. It may ever last more than 5 minutes because I am a generous man. :smile:

**Comment by lduguid** [comment]
Naive question, and my apologies if has been asked before but it seems at times that the 'sniff' data from retail of yester. year is highly sought after information to assist in achieving the original state of the game etc.  Is there a reason that this sniff data cannot be publicly published somewhere for all to see. I realize that it is niche information and that requires expertise and experience to parse the nuggets of useful data into something meaningful. Is it for copyright reasons?

**Comment by cala** [comment]
There are two main reasons.

As you guessed, the first one is legal: sniff data contain copyrighted material from Blizzard (such as texts) and other proprietary data, like the ones used in their protocols. Also, sniffing data or sharing them is forbidden by the terms of the EULA every WoW player accepted.

The second reason is privacy. The sniff data contain everything, including private data about the player and the people he/she is playing with. Usually people do not want those data to become public for obvious reasons. We could think of sharing sniff data without those privates things, but that would require to parse the sniffs to remove them and even those private data are valuable for developers, for example if someone is working on the login/logout system. So it is best to not remove anything from the whole sniff because every bit may be useful. As such, they can not be shared because of privacy issues.

There are also other reasons, more debatable.

Knowledge is power. And some people do not share their sniffs because they can say that their server/database/whatever is better than some "competitors", thanks to the use of sniff data instead of less accurate material like screenshots of videos.

To be useful, sniffs must be parsed and writing a parser is not an easy job. Some people do not want others to use freely their work like "hey, give me your parser, so I can develop for myself and share nothing with you though you did the hard job".

**Comment by cala** [comment]
@evil-at-wow and @Tobschinski kindly asking if you had the time to check/parse those data please? I'm almost done with the changes for Stratholme and I should then switch back to Blackrock Spire (DB and SD2) or Dire Maul (but I lack data there). Thanks!

**Comment by evil-at-wow** [comment]
Actually, I was assuming that @Tobschinski was going to do that, because even he has the data this time around. But it appears that I can still win your 5 minutes of eternal love and admiration even though I gave him a a head start of more than a month! :stuck_out_tongue: 

On a more serious note: not yet, because getting data like this is still a pain and sometimes rather time consuming with my current tools. I'm trying to update them a bit to make them more powerful. But I'll have a look soon(ish).

**Comment by Tobschinski** [comment]
Well, this will be fun.

| - | e | x | y | z | o |
| --- | --- | --- | --- | --- | --- |
| a | 9819 | 163.3209 | -340.9818 | 111.0216 | 4.818223 |
| b | 9819 | 164.2471 | -339.0313 | 111.0368 | 1.413717 |
| c | 9819 | 161.124 | -339.5178 | 111.0381 | 3.001966 |
| d | 10317 | 162.5045 | -337.8101 | 111.0367 | 4.13643 |
| e | 9819 | 160.9896 | -337.7715 | 111.0368 | 1.117011 |
| f | 9819 | 161.8347 | -335.7923 | 111.0352 | 2.286381 |

| - | e | x | y | z | o |
| --- | --- | --- | --- | --- | --- |
| g | 9819 | 113.9726 | -366.0805 | 116.9195 | 6.252025 |
| h | 9819 | 112.7245 | -368.9635 | 116.9307 | 4.677482 |
| i | 9819 | 110.5757 | -368.2123 | 116.9278 | 4.310963 |
| j | 10317 | 109.3343 | -366.4785 | 116.9261 | 2.740167 |
| k | 9819 | 110.1331 | -363.9824 | 116.9272 | 0.5235988 |
| l | 9819 | 111.9971 | -363.0948 | 116.929 | 5.951573 |

They spawn with the first wave spawning inside the stadium and despawn when Rend dies.

---

Leader Creature A

| - | x | y | z | - |
| --- | --- | --- | --- | --- |
| a | 165.1338 | -358.0481 | 116.8369 |  |
| a | 165.8434 | -372.4112 | 116.8156 |  |
| a | 165.2259 | -384.015 | 121.9753 |  |
| a | 164.5799 | -389.8949 | 121.9748 |  |
| a | 160.6099 | -392.7337 | 121.975 |  |
| a | 160.619 | -395.826 | 121.9752 | LAST POINT |

Follower Creature B-F

| - | x | y | z | o | - |
| --- | --- | --- | --- | --- | --- |
| b | 162.1428 | -395.1175 | 121.9751 | -1.67753 | LAST POINT |
| c | 158.6822 | -395.7097 | 121.9753 | -1.787977 | LAST POINT |
| d | 164.384 | -395.3787 | 121.9751 | -1.502597 | LAST POINT |
| e | 156.9669 | -395.2188 | 121.9752 | -1.678662 | LAST POINT |
| f | 166.2515 | -395.0366 | 121.975 | -1.791467 | LAST POINT |

---

Leader Creature G

| - | x | y | z | - |
| --- | --- | --- | --- | --- |
| g | 126.1305 | -366.4595 | 116.8424 |  |
| g | 133.2055 | -365.9101 | 116.84 |  |
| g | 138.1459 | -367.2293 | 116.8409 |  |
| g | 138.3509 | -372.4112 | 116.8156 |  |
| g | 138.5888 | -378.5246 | 119.0878 |  |
| g | 138.9185 | -382.6654 | 121.9623 |  |
| g | 139.1318 | -390.8854 | 121.9747 |  |
| g | 143.6053 | -394.0254 | 121.9751 |  |
| g | 143.814 | -396.7092 | 121.9753 | LAST POINT |

Follower Creature H-L

| - | x | y | z | o | - |
| --- | --- | --- | --- | --- | --- |
| h | 145.3893 | -396.1959 | 121.9752 | -1.419479 | LAST POINT |
| i | 142.1598 | -396.0284 | 121.9752 | -1.661444 | LAST POINT |
| j | 147.7274 | -396.3042 | 121.9753 | -1.40136 | LAST POINT |
| k | 139.9446 | -396.7277 | 121.9753 | -1.428414 | LAST POINT |
| l | 149.3754 | -395.7497 | 121.9753 | -1.714769 | LAST POINT |

**Comment by Tobschinski** [comment]
ph

**Comment by cala** [comment]
Thanks @Tobschinski !

**Comment by Tobschinski** [comment]
What a wonderful guy this @Tobschinski is.

**Comment by cala** [comment]
Everybody love him, indeed.

**Comment by cala** [comment]
Closed by https://github.com/cmangos/mangos-classic/commit/4ef0fb89dd7ebc108383e2c60074e01b5e50be2a
Thanks everyone! :+1:
