### ISSUE TITLE
Wrong 100% drop chance for Humbert's Sword (Dun Garok)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#865]
The chance should be very low according to wowhead comments. Even 8% might be too high.

UPDATE creature_loot_template SET ChanceOrQuestChance=-8 WHERE item=3693 AND ChanceOrQuestChance=-100;

By the way, big thanks for hard work on the DB, @cala and @Tobschinski. Recently imported/converted almost a year of commits checking lots of them, and it seems impressing.

**Comment by Zooke** [comment]
Judging from the comments on different sites, the drop rate was very low in 1.12
https://web.archive.org/web/20080420174835/http://wow.allakhazam.com/db/quest.html?source=live;wquest=547
8%, although fair, still feels too high for a quest that seems notorious for it's drop rate (and a quest few people actually did because of the group nature and not great rewards). 3-4% is probably more like how it really was.

**Comment by Muehe** [comment]
We might want to keep in mind that not everybody was on this quest when killing those NPCs. This is after all a Horde quest in an Alliance quest area.
