### ISSUE TITLE
Highlord Taelan Fordring Bugged

### ISSUE THREAD

**Issue by Zooke** [classicdb/database#867]
Highlord Taelan Fordring stops fighting at around 30/40% hp and just stands there.
He is also assigned as '2' in the civilian tab, Is 2 a valid entry ? He is the only npc in the database marked as such.

**Comment by cala** [comment]
The civilian value is an error. Taelan is not a civilian. He is not a PvP target either...
Regarding the fight, chances are very high this come from the SD2 script that does not expect Taelan to take so much damage because it was written initially for WotLK where the NPCs attacking Taelan are no longer elites. I'm on it.

**Comment by cala** [comment]
I was both right and wrong.
Wrong because the NPCs are still elites in WotLK.
Right as the SD2 script is at fault because it does not expect Taelan to go below 50% HP before facing Isillien. Unfortunately, it can happen in the current state of Classic DB: the involved NPCs stats are wrong resulting in a big damage input right at the start of the event, preventing Taelan to even heal himself. He is supposed to heal below 75%HP and stop his AI below 50% HP. Currently, the 5 elites attacking him quickly drop his HPs to 50%, making him stuck until death.

I can (and will) fix it by DB with correct stats, but I think a safeguard in the SD2 script would also be nice. Here is my proposal. What do you think @xfurry ?

``` diff
--- a/src/scriptdev2/scripts/eastern_kingdoms/western_plaguelands.cpp
+++ b/src/scriptdev2/scripts/eastern_kingdoms/western_plaguelands.cpp
@@ -230,6 +230,7 @@ struct npc_taelan_fordringAI: public npc_escortAI, private DialogueHelper
         m_bFightStarted = false;
         m_bTaelanDead = false;
         m_bHasMount = false;
+        m_bIsEligibleToDeath = false;
         Reset();
     }

@@ -237,6 +238,7 @@ struct npc_taelan_fordringAI: public npc_escortAI, private DialogueHelper
     bool m_bFightStarted;
     bool m_bHasMount;
     bool m_bTaelanDead;
+    bool m_bIsEligibleToDeath;

     ObjectGuid m_isillenGuid;
     ObjectGuid m_tirionGuid;
@@ -452,6 +454,9 @@ struct npc_taelan_fordringAI: public npc_escortAI, private DialogueHelper
             case SAY_REACH_TOWER:
                 // start fight event
                 m_creature->SummonCreature(NPC_ISILLIEN, 2693.12f, -1943.04f, 72.04f, 2.11f, TEMPSUMMON_TIMED_OOC_OR_DEAD_DESPAWN, 15 * MINUTE * IN_MILLISECONDS);
+                // Now that Isillien is spawned, we can allow Taelan to "die" (feign death)
+                // or it will break his combat script if he takes too much damage before that point
+                m_bIsEligibleToDeath = true;
                 break;
             case SAY_ISILLIEN_2:
                 if (Creature* pIsillien = m_creature->GetMap()->GetCreature(m_isillenGuid))
@@ -557,7 +562,7 @@ struct npc_taelan_fordringAI: public npc_escortAI, private DialogueHelper
         if (m_bTaelanDead)
             return;

-        if (!m_bTaelanDead && m_creature->GetHealthPercent() < 50.0f)
+        if (!m_bTaelanDead && m_creature->GetHealthPercent() < 50.0f && m_bIsEligibleToDeath) // Don't allow Taelan to "die" before Isillien is spawned
         {
             StartNextDialogueText(SAY_KILL_TAELAN_1);
             m_bTaelanDead = true;
--
```
