### ISSUE TITLE
Wrong 100% drop chance for Mature Blue Dragon Sinew from Cobalt dragonkin (Winterspring)

### ISSUE THREAD

**Issue by Neotmiren** [classicdb/database#872]
Should be very low. The only 100% drop - from Azuregos. 0.1% is YTDB value.

``` sql
UPDATE creature_loot_template SET ChanceOrQuestChance=-0.1 WHERE item=18704 AND entry!=6109 AND ChanceOrQuestChance=-100; -- all dragonkin except Azuregos
```

**Comment by dagochen** [comment]
Why negative? Its not a questdrop. It should be worlddrop if I am right.

**Comment by Neotmiren** [comment]
I am also not sure about this and at first used positive value. But all values are currently negative in DB (including Azuregos) and it is "quest item" in item_template (and in old allakhazam database too). Do any other quest items exist that drop without quest?

If some evidence (Classic time internet page link) could be found then its chances must be changed to positive, of course.

**Comment by Neotmiren** [comment]
YTDB also has negative values, although only 50% drop chance in case of Azuregos, which contradicts to

"Drops rate is 100% from Azuregos"
http://wowwiki.wikia.com/wiki/Mature_Blue_Dragon_Sinew?oldid=345177

**Comment by Tobschinski** [comment]
Well, I'm reading comments that mages, warrior, shamans, even deathknights got this item to drop. They can't have access to hunter quests ...

**Comment by Neotmiren** [comment]
"Now why can all classes start the quest but only hunters use the bag? also its bop so"
http://web.archive.org/web/20060520171445/http://wow.allakhazam.com/db/quest.html?wquest=7634

**Comment by dagochen** [comment]
what about the priest epic quest item? maybe compare them....

**Comment by Phatcat** [comment]
http://web.archive.org/web/20060612224057/http://wow.allakhazam.com/db/item.html?witem=18704

Every class can pick up this item; it is tradable. Don't need to be on any quest for it.

**Comment by Phatcat** [comment]
the 0.1 for this mob seems fine, but 100% for azuregos? why does allakhazam list about 50%, then?

**Comment by Phatcat** [comment]
~~Tobs; actually, it's not a hunter quest, it's just a quest with only a hunter reward; pretty sure the quest can be started by anyone.~~ - And so it indeed actually is a hunter class quest.
Neo, you misunderstand your quote there; it is the bag that is bop, not the dragon sinew.

**Comment by Neotmiren** [comment]
@Phatcat, some quest items seems to be tradable (with bonding=0, which is unusual). I added this quest item and successfully traded it with playerbot character.

In case of Azuregos Blizzard could change chance from 50% to 100%. wowwiki
statement in 2006 is 100%.

**Comment by Neotmiren** [comment]
@dagochen, The Eye of Shadow and The Eye of Shadow are not quest items and so it is natural that they are not quest drop.

**Comment by dagochen** [comment]
There are more than enough comments of non-hunters who picked that item up while farming or doing quests in winterspring. I am 99.9% sure a mage would not have a quest where he gets a epic quiver in his questlog.  Furthermore I really doubt people could get that quest at all, since you needed to be able to talk to the trees in felwood. And that was (again 99.9% sure!) only possible as hunter if you had picked up the ancient leaf from majordomus.

**Comment by Tobschinski** [comment]
> Tobs; actually, it's not a hunter quest, it's just a quest with only a hunter reward; pretty sure the quest can be started by anyone.

How, you cannot just take these quests, you gotta have the leaf from MC.

**Comment by Neotmiren** [comment]
Somehow or other, the chance should be changed positive because with current quest settings in DB it would be impossible to get this quest for other classes. Also non-quest drop is more interesting: the item might drop from dragonkin even before level 60.

**Comment by Phatcat** [comment]
Actually, I was going by the comment by Neo; never played a hunter past level 35 myself.

Looking at the quest on allakhazam it quite clearly says 'hunter quest' and yes, class quests are exclusive to their classe - should have probably checked that before chipping in, so sorry about that one. Does not invalidate the other stuff I say, though.

Also where does the wiki have the 100% drop chance from? - for drop chances wikis are not really that reliable.

**Comment by Phatcat** [comment]
> some quest items seems to be tradable

A lot of quest items are tradable; Think about the darkmoon faire cards that can be turned into decks, those are probably the closest in comparison to this; those are also very tradable.

**Comment by Phatcat** [comment]
@dagochen You giving someone a thumbs up for correcting something unrelated which I said that turned out not to be true? - even after I basically just corrected all of you with my first comment? - A comment noone seems to care about, though. So much so that only  OP has even pretended it to exist.

Only Neo has even achnowledged the comment and very reluctantly agreed he was wrong; if you guys would just read my comment the matter of the quest itself would be pointless in this regard as the sinew dropping is not tied to any quest whatsoever.

**Comment by Neotmiren** [comment]
@Phatcat, I (am not "Neo") read your link before you posted it. What I have understood from this small investigation (which was neccessary because changing current state of DB without understanding is not good practice):

1) There are two definitions of "Quest Item". First is by `bonding` field and second is by `class` field of item_template.

2) WoW client does not show "Quest Item" label for quest items with bonding=0. Allakhazam probably shows them just by `class` ignoring bonding field, which could be really misleading. Mature Blue Dragon Sinew is labeled as Quest Item there, but is not labeled in client! So it is just not a real Quest item. But nevertheless, for some reason, it had become quest drop in WoW databases...

3) There are probably no real (labeled) Quest Items that could be dropped while not on related quest. This starting point seems to be correct, but Mature Blue Dragon Sinew is not such an item.

4) Items like Darkmoon Faire card are NOT Quest Items by any of these two definitions (they are Miscellaneous:Junk). The correct analogue to "Mature Blue Dragon Sinew" is "Gorilla Fang", for example.

**Comment by Phatcat** [comment]
**Neo**tmiren.
Frankly, you get offended by me calling you Neo, the first 3 letters of your git handle, I couldn't care less about.

http://www.wowhead.com/item=2799/gorilla-fang

http://wowwiki.wikia.com/wiki/Gorilla_Fang?oldid=689487

Notice how the old link doesn't state in the tooltip that it's a quest item either; that is something new blizzard must have started doing after wrath.

Gorilla fang can be vendored, just like the Darkmoon Cards/Decks. Also they are not to be considered quest items, but rather items you can use in a quest, much more akin to the evil bat eye, etc (which was later turned grey since the quests got removed)

http://www.wowhead.com/item=11404/evil-bat-eye#comments

Sinews cannot be vendored nor sold. I am not sure what they are really akin to, tbh.

**Comment by Phatcat** [comment]
Possibly this is one of the closer relatives; another 'quest' item which cannot be vendored but traded; http://wowwiki.wikia.com/wiki/Indurium_Ore

**Comment by Phatcat** [comment]
Also, the 100% drop for Azure comes directly from the patchnotes so you are right about that one :+1:
http://wowwiki.wikia.com/wiki/Mature_Blue_Dragon_Sinew

> Patch 1.5.0 (2005-06-07): Mature Blue Dragon Sinew can both now drop off appropriate level blue dragonkin monsters. It should be noted that Azuregos will guarantee a drop but to get it from the lesser creatures will be a much rarer occurrence.

Yes. I will also call Azuregos for Azure if I wanna.

**Comment by dagochen** [comment]
So its Hunter only quest but everybody can pick it up and find it. Thats why i thumb up Tobchinskis post...it is as I posted in my first post btw ;) And also the way you said phatcat in your first post. The tag "quest" on allakhazam and the "classes: mage, shaman, druid, ...." on it is confusing and can be ignored, since its equal to "all classes". Sorry if i made it more confusing :P
